#!/usr/bin/env -S npx tsx
/*
 * selftest — proves the pipeline without the Plus:
 *   1. frame encode/decode round-trip (pure TS)
 *   2. compile testapp/hello.c with Retro68 (no Claude) -> real .bin -> frame
 *   3. with ANTHROPIC_API_KEY: the full MAKE pipeline (Claude writes an app,
 *      compile w/ retry) — prints name, size, attempts. Costs tokens + ~1-3 min.
 *      Skip with FOUNDRY_SKIP_LIVE=1.
 */

import './main-env.ts';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { encodeBin, checksum16 } from './frame.ts';
import { compileApp, toolchainAvailable } from './compile.ts';
import { generateApp } from './codegen.ts';

let failures = 0;
function check(name: string, ok: boolean, detail = ''): void {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
  if (!ok) failures++;
}

/** Decode an FNDBIN frame back to bytes (a TS twin of foundry_rx.inc). */
function decodeFrame(frame: string): Buffer {
  const lines = frame.split('\r\n');
  const head = lines[0].match(/^FNDBIN (\d+) (\d+)$/);
  if (!head) throw new Error('bad header');
  const total = parseInt(head[1], 10);
  const sum = parseInt(head[2], 10);
  const hex = lines.slice(1, -2).join('');
  if (lines[lines.length - 2] !== 'FNDEND') throw new Error('no FNDEND');
  const buf = Buffer.from(hex, 'hex');
  if (buf.length !== total) throw new Error(`length ${buf.length} != ${total}`);
  if (checksum16(buf) !== sum) throw new Error('checksum mismatch');
  return buf;
}

// ---- 1. frame round-trip ----
const sample = Buffer.from(Array.from({ length: 300 }, (_, i) => (i * 37 + 11) & 0xff));
const rt = decodeFrame(encodeBin(sample));
check('frame round-trip', rt.equals(sample));

// ---- 2. offline compile of the skeleton ----
const here = dirname(fileURLToPath(import.meta.url));
if (!toolchainAvailable()) {
  console.log('(Retro68 toolchain not found — skipping compile tests)');
} else {
  const hello = readFileSync(join(here, '..', 'testapp', 'hello.c'), 'utf8');
  const res = await compileApp('Hello', hello);
  check('skeleton compiles', res.ok, res.ok ? '' : (res.errors ?? '').split('\n')[0]);
  if (res.ok && res.bin) {
    check('bin is MacBinary', res.bin.length > 1000 && res.bin[0] === 0);
    const frame = encodeBin(res.bin);
    check('bin frames + decodes', decodeFrame(frame).equals(res.bin));
    // stash for the Plus-side offline test build
    const outPath = process.argv[2];
    if (outPath) {
      const esc = frame.replace(/\r\n/g, '\\r\\n"\n"');
      writeFileSync(
        outPath,
        `/* generated by agent-foundry selftest — a real FND frame delivering Hello */\nstatic const char gTestFrame[] =\n"${esc}";\n`
      );
      console.log(`(wrote embedded test frame -> ${outPath})`);
    }
  }
}

// ---- 3. live: the whole point ----
if (process.env.FOUNDRY_SKIP_LIVE === '1') {
  console.log('(FOUNDRY_SKIP_LIVE=1 — skipping live MAKE)');
} else if (!process.env.ANTHROPIC_API_KEY) {
  console.log('(no ANTHROPIC_API_KEY — skipping live MAKE)');
} else if (toolchainAvailable()) {
  const wish = process.argv[3] ?? 'a dice roller: click to roll two big dice, shows totals and a roll count';
  console.log(`\n--- live MAKE: "${wish}" ---`);
  let prior: { code: string; errors: string } | undefined;
  let delivered = false;
  for (let attempt = 1; attempt <= 4 && !delivered; attempt++) {
    const gen = await generateApp(wish, prior, (s) => console.log(`  ...writing (${s}s)`));
    console.log(`  attempt ${attempt}: ${gen.name}, ${gen.code.split('\n').length} lines`);
    const res = await compileApp(gen.name, gen.code);
    if (res.ok && res.bin) {
      check('live MAKE compiles', true, `${gen.name}: ${res.bin.length} bytes, attempt ${attempt}`);
      writeFileSync(`/tmp/foundry-${gen.name}.bin`, res.bin);
      console.log(`  saved /tmp/foundry-${gen.name}.bin (inspect or inject by hand)`);
      delivered = true;
    } else {
      console.log(`  compile errors:\n${(res.errors ?? '').split('\n').slice(0, 8).map((l) => '    ' + l).join('\n')}`);
      prior = { code: gen.code, errors: res.errors ?? '' };
    }
  }
  if (!delivered) check('live MAKE compiles', false, 'no clean build in 4 attempts');
}

console.log(failures === 0 ? '\nALL CHECKS PASSED' : `\n${failures} CHECK(S) FAILED`);
process.exit(failures === 0 ? 0 : 1);
