/* Phase 3 diff test: a small change yields a small dirty rect, applying the rect
 * reproduces the new frame. Also emits porthole/test_diff.h (a full frame + a
 * dirty-rect frame) for the Plus-side rect-apply regression test in rxtest.c. */
import { go, click, typeText, shot, CW, CH, CRB, shutdown } from './browser.ts';
import { dirtyRect } from './diff.ts';
import { frameFull, frameRect } from './frame.ts';
import { writeFileSync } from 'node:fs';

function apply(base: Buffer, d: any): Buffer {
  const out = Buffer.from(base);
  for (let r = 0; r < d.h; r++) d.rect.copy(out, (d.y + r) * CRB + (d.x >> 3), r * d.rb, (r + 1) * d.rb);
  return out;
}
const carr = (name: string, buf: Buffer) => {
  let s = `static unsigned char ${name}[${buf.length}] = {\n`;
  for (let i = 0; i < buf.length; i++) s += (i % 16 === 0 ? '  ' : '') + buf[i] + (i < buf.length - 1 ? ',' : '') + (i % 16 === 15 ? '\n' : '');
  return s + '\n};\n';
};
async function main() {
  let pass = 0, fail = 0;
  const ok = (n: string, c: boolean) => { c ? pass++ : fail++; console.log((c ? 'ok  ' : 'FAIL') + ' ' + n); };
  await go('file://' + process.cwd() + '/test/click.html');
  await click(60, 159);
  const a = await shot();
  await typeText('X');
  const b = await shot();

  const d = dirtyRect(a, b, CW, CH, CRB);
  ok('change yields a rect (not full/none): ' + d.kind, d.kind === 'rect');
  if (d.kind === 'rect') {
    ok(`rect is small (${d.w}x${d.h} = ${d.w * d.h}px, < 20% screen)`, d.w * d.h < CW * CH * 0.2);
    ok('x and w are byte-aligned', (d.x % 8 === 0) && (d.w % 8 === 0));
    ok('applying the rect to A reproduces B exactly', apply(a, d).equals(b));
    writeFileSync('../porthole/test_diff.h',
      `/* generated by difftest: a full frame + a one-keystroke dirty-rect frame, for rxtest */\n` +
      `#define DIFF_RX ${d.x}\n#define DIFF_RY ${d.y}\n#define DIFF_RW ${d.w}\n#define DIFF_RH ${d.h}\n` +
      carr('gDiffFull', frameFull(a, CW, CH, CRB)) + carr('gDiffRect', frameRect(d.rect, d.x, d.y, d.w, d.h, d.rb)));
    console.log('wrote ../porthole/test_diff.h');
  }
  await shutdown();
  console.log(`\ndifftest: ${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}
main();
