#!/usr/bin/env python3
"""
Atkinson dither prototype for the Macinclaude "Atkinson" app.

Turns any image into a 512x342 1-bit bitmap the way Bill Atkinson's dithering
did on the original Mac. This is the aesthetic-validation prototype: it writes
a PNG preview you can eyeball. The proven algorithm gets ported to the mini's
TypeScript later; the packed 1bpp output here also defines the wire format the
Mac Plus will consume (MSB-first, row-padded to a byte boundary).

Usage:
  python3 dither.py INPUT.png [OUTPUT_PREVIEW.png] [--fit contain|cover]
      [--contrast 1.0] [--bin OUT.bin]

512x342 = the Mac Plus screen. 1bpp, MSB-first, each row padded to whole bytes
(512/8 = 64 bytes per row exactly) -> 64*342 = 21888 bytes per full image.
"""
import sys
from PIL import Image, ImageEnhance, ImageOps

W, H = 512, 342  # Mac Plus screen; override with --size WxH

def load_gray_fit(path, fit, contrast):
    im = Image.open(path).convert("L")
    if contrast != 1.0:
        im = ImageEnhance.Contrast(im).enhance(contrast)
    if fit == "cover":
        # fill the whole 512x342 frame, center-crop the overflow
        im = ImageOps.fit(im, (W, H), method=Image.LANCZOS, centering=(0.5, 0.5))
        canvas = im
    else:
        # contain: scale to fit, paste centered on white (classic Mac margins)
        im.thumbnail((W, H), Image.LANCZOS)
        canvas = Image.new("L", (W, H), 255)
        canvas.paste(im, ((W - im.width) // 2, (H - im.height) // 2))
    return canvas

def atkinson(im):
    """Atkinson dither: threshold at 128, propagate 1/8 of the error to 6
    neighbors (only 6/8 total -> the signature crisp, contrasty Mac look)."""
    px = list(im.getdata())  # 0..255 row-major
    w, h = im.width, im.height
    def at(x, y):
        return y * w + x
    out = bytearray(w * h)  # 0 (black) or 1 (white)
    buf = [float(v) for v in px]
    for y in range(h):
        for x in range(w):
            i = at(x, y)
            old = buf[i]
            new = 255 if old >= 128 else 0
            out[i] = 1 if new == 255 else 0
            err = (old - new) / 8.0
            for dx, dy in ((1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h:
                    buf[at(nx, ny)] += err
    return out  # 1 = white pixel, 0 = black pixel

def to_preview(bits, w, h):
    im = Image.new("1", (w, h))
    im.putdata([1 if b else 0 for b in bits])
    return im

def pack_1bpp(bits, w, h):
    """MSB-first, rows padded to whole bytes. On the Mac, a SET bit = black,
    so we invert (bit 1 => black). Matches QuickDraw 1-bit convention."""
    row_bytes = (w + 7) // 8
    out = bytearray(row_bytes * h)
    for y in range(h):
        for x in range(w):
            white = bits[y * w + x]
            if not white:  # black pixel -> set the bit
                out[y * row_bytes + (x >> 3)] |= (0x80 >> (x & 7))
    return out, row_bytes

def emit_header(path, packed, w, h, rb, name):
    lines = [
        "/* Generated by dither.py - do not edit. A 1bpp Atkinson-dithered test",
        f" * image, {w}x{h}, MSB-first, set bit = black (QuickDraw convention),",
        f" * {rb} bytes/row ({len(packed)} bytes total). Used to verify the Plus",
        " * renderer without a live serial link. */",
        f"#define {name}_W {w}",
        f"#define {name}_H {h}",
        f"#define {name}_ROWBYTES {rb}",
        f"static const unsigned char {name}[{len(packed)}] = {{",
    ]
    for off in range(0, len(packed), 16):
        chunk = packed[off:off+16]
        lines.append("  " + ",".join(str(b) for b in chunk) + ",")
    lines.append("};")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")

def main():
    global W, H
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    inp = sys.argv[1]
    out_png = None
    fit, contrast, out_bin, out_hdr, hdr_name = "contain", 1.0, None, None, "gTestImg"
    rest = sys.argv[2:]
    i = 0
    while i < len(rest):
        a = rest[i]
        if a == "--fit": fit = rest[i+1]; i += 2
        elif a == "--contrast": contrast = float(rest[i+1]); i += 2
        elif a == "--bin": out_bin = rest[i+1]; i += 2
        elif a == "--header": out_hdr = rest[i+1]; i += 2
        elif a == "--name": hdr_name = rest[i+1]; i += 2
        elif a == "--size":
            W, H = (int(v) for v in rest[i+1].lower().split("x")); i += 2
        elif not a.startswith("--") and out_png is None: out_png = a; i += 1
        else: i += 1
    if out_png is None:
        out_png = inp.rsplit(".", 1)[0] + "_1bit.png"

    im = load_gray_fit(inp, fit, contrast)
    bits = atkinson(im)
    preview = to_preview(bits, W, H)
    preview.save(out_png)
    print(f"preview: {out_png}  ({W}x{H} 1-bit, fit={fit}, contrast={contrast})")
    packed, rb = pack_1bpp(bits, W, H)
    if out_bin:
        with open(out_bin, "wb") as f:
            f.write(packed)
        print(f"packed: {out_bin}  ({len(packed)} bytes, {rb} bytes/row)")
    if out_hdr:
        emit_header(out_hdr, packed, W, H, rb, hdr_name)
        print(f"header: {out_hdr}  ({hdr_name}, {len(packed)} bytes)")

if __name__ == "__main__":
    main()
