/*
 * gpt.c -- int8 llama2 inference for THE ORACLE (Mac Plus / Retro68), v2.
 * GENERATED by make_gpt.py from ../llama2.c/runq.c. Do not hand-edit.
 * Loads weights from an in-RAM buffer (embedded 'MODL'/'TOKN' resources), so
 * there is no file I/O and no big single allocation -- fits the 4MB Plus.
 * v2: 68000 speed pass (muls.w matmul, RoPE tables, prefill classifier skip,
 * top-k sampler, tick/abort callback). See make_gpt.py.
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include "gpt.h"

int GS = 0; // group size global for quantization of the weights

// ----------------------------------------------------------------------------
// Transformer model

typedef struct {
    int dim; // transformer dimension
    int hidden_dim; // for ffn layers
    int n_layers; // number of layers
    int n_heads; // number of query heads
    int n_kv_heads; // number of key/value heads (can be < query heads because of multiquery)
    int vocab_size; // vocabulary size, usually 256 (byte-level)
    int seq_len; // max sequence length
} Config;

typedef struct {
    int8_t* q;    // quantized values
    float* s; // scaling factors
} QuantizedTensor;

typedef struct {
    // token embedding table
    QuantizedTensor *q_tokens; // (vocab_size, dim)
    float* token_embedding_table; // same, but dequantized

    // weights for rmsnorms
    float* rms_att_weight; // (layer, dim) rmsnorm weights
    float* rms_ffn_weight; // (layer, dim)
    // weights for matmuls. note dim == n_heads * head_size
    QuantizedTensor *wq; // (layer, dim, n_heads * head_size)
    QuantizedTensor *wk; // (layer, dim, n_kv_heads * head_size)
    QuantizedTensor *wv; // (layer, dim, n_kv_heads * head_size)
    QuantizedTensor *wo; // (layer, n_heads * head_size, dim)
    // weights for ffn
    QuantizedTensor *w1; // (layer, hidden_dim, dim)
    QuantizedTensor *w2; // (layer, dim, hidden_dim)
    QuantizedTensor *w3; // (layer, hidden_dim, dim)
    // final rmsnorm
    float* rms_final_weight; // (dim,)
    // (optional) classifier weights for the logits, on the last layer
    QuantizedTensor *wcls;
} TransformerWeights;

typedef struct {
    // current wave of activations
    float *x; // activation at current time stamp (dim,)
    float *xb; // same, but inside a residual branch (dim,)
    float *xb2; // an additional buffer just for convenience (dim,)
    float *hb; // buffer for hidden dimension in the ffn (hidden_dim,)
    float *hb2; // buffer for hidden dimension in the ffn (hidden_dim,)
    QuantizedTensor xq; // quantized x (dim,)
    QuantizedTensor hq; // quantized hb (hidden_dim,)
    float *q; // query (dim,)
    float *k; // key (dim,)
    float *v; // value (dim,)
    float *att; // buffer for scores/attention values (n_heads, seq_len)
    float *logits; // output logits
    // kv cache
    float* key_cache;   // (layer, seq_len, dim)
    float* value_cache; // (layer, seq_len, dim)
} RunState;

typedef struct {
    Config config; // the hyperparameters of the architecture (the blueprint)
    TransformerWeights weights; // the weights of the model
    RunState state; // buffers for the "wave" of activations in the forward pass
    // some more state needed to properly clean up the memory mapping (sigh)
    int fd; // file descriptor for memory mapping
    float* data; // memory mapped data pointer
    long file_size; // size of the checkpoint file in bytes
} Transformer;

void malloc_run_state(RunState* s, Config* p) {
    // we calloc instead of malloc to keep valgrind happy
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    s->x = calloc(p->dim, sizeof(float));
    s->xb = calloc(p->dim, sizeof(float));
    s->xb2 = calloc(p->dim, sizeof(float));
    s->hb = calloc(p->hidden_dim, sizeof(float));
    s->hb2 = calloc(p->hidden_dim, sizeof(float));
    s->xq = (QuantizedTensor) { .q = calloc(p->dim, sizeof(int8_t)), .s = calloc(p->dim, sizeof(float)) };
    s->hq = (QuantizedTensor) { .q = calloc(p->hidden_dim, sizeof(int8_t)), .s = calloc(p->hidden_dim, sizeof(float)) };
    s->q = calloc(p->dim, sizeof(float));
    s->k = calloc(kv_dim, sizeof(float));
    s->v = calloc(kv_dim, sizeof(float));
    s->att = calloc(p->n_heads * p->seq_len, sizeof(float));
    s->logits = calloc(p->vocab_size, sizeof(float));
    s->key_cache = calloc(p->n_layers * p->seq_len * kv_dim, sizeof(float));
    s->value_cache = calloc(p->n_layers * p->seq_len * kv_dim, sizeof(float));
    // ensure all mallocs went fine
    if (!s->x || !s->xb || !s->xb2 || !s->hb || !s->hb2 || !s->q
     || !s->k || !s->v || !s->att || !s->logits || !s->key_cache
     || !s->value_cache) {
        fprintf(stderr, "malloc failed!\n");
        exit(EXIT_FAILURE);
    }
}

void free_run_state(RunState* s) {
    free(s->x);
    free(s->xb);
    free(s->xb2);
    free(s->hb);
    free(s->hb2);
    free(s->xq.q);
    free(s->xq.s);
    free(s->hq.q);
    free(s->hq.s);
    free(s->q);
    free(s->k);
    free(s->v);
    free(s->att);
    free(s->logits);
    free(s->key_cache);
    free(s->value_cache);
}
void dequantize(QuantizedTensor *qx, float* x, int n) {
    for (int i = 0; i < n; i++) {
        x[i] = qx->q[i] * qx->s[i / GS];
    }
}

void quantize(QuantizedTensor *qx, float* x, int n) {
    int num_groups = n / GS;
    float Q_MAX = 127.0f;

    for (int group = 0; group < num_groups; group++) {

        // find the max absolute value in the current group
        float wmax = 0.0;
        for (int i = 0; i < GS; i++) {
            float val = fabs(x[group * GS + i]);
            if (val > wmax) {
                wmax = val;
            }
        }

        // calculate and write the scaling factor
        float scale = wmax / Q_MAX;
        qx->s[group] = scale;

        // calculate and write the quantized values
        for (int i = 0; i < GS; i++) {
            float quant_value = x[group * GS + i] / scale; // scale
            int8_t quantized = (int8_t) round(quant_value); // round and clamp
            qx->q[group * GS + i] = quantized;
        }
    }
}

/* initialize `n` x quantized tensor (with `size_each` elements), starting from memory pointed at *ptr */
QuantizedTensor *init_quantized_tensors(void **ptr, int n, int size_each) {
    void *p = *ptr;
    QuantizedTensor *res = malloc(n * sizeof(QuantizedTensor));
    for(int i=0; i<n; i++) {
        /* map quantized int8 values*/
        res[i].q = (int8_t*)p;
        p = (int8_t*)p + size_each;
        /* map scale factors */
        res[i].s = (float*)p;
        p = (float*)p + size_each / GS;
    }
    *ptr = p; // advance ptr to current position
    return res;
}

/* optional progress hook (for the app's loading UI / remote diagnosis) */
void (*gGptProgress)(int step) = 0;
#define PROG(n) do { if (gGptProgress) gGptProgress(n); } while (0)

/* generation-time knobs & tables (v2 engine) */
int gWantLogits = 1;              /* 0 during prompt prefill: skip classifier */
static float gAttnScale = 1.0f;   /* sqrtf(head_size), hoisted out of attention */
static float *gRopeCos = 0L, *gRopeSin = 0L;   /* [seq_len][head_size/2] */

/* int8 x int8 product table (v3 speed): the 68000's MULS.W is ~50 cycles; a
 * table read is ~2x faster and BYTE-IDENTICAL (same products), so the model
 * output is unchanged. 65536 entries x int16 = 128KB, built once at init.
 * Index = ((uint8)a << 8) | (uint8)b, value = (int8)a * (int8)b. */
static int16_t *gMulLUT = 0L;
static int build_mul_lut(void) {
    int a, b;
    gMulLUT = (int16_t *)malloc(65536L * sizeof(int16_t));
    if (!gMulLUT) return -1;
    for (a = -128; a < 128; a++)
        for (b = -128; b < 128; b++)
            gMulLUT[(((long)(a & 0xFF)) << 8) | (b & 0xFF)] = (int16_t)(a * b);
    return 0;
}

static int big_endian(void) { unsigned short x = 1; return *((unsigned char *)&x) == 0; }
static uint32_t rd32(const unsigned char *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static float rdf(const unsigned char *p) {
    uint32_t u = rd32(p); float f; memcpy(&f, &u, 4); return f;
}
static void swap4(void *v) {
    unsigned char *b = (unsigned char *)v, t;
    t = b[0]; b[0] = b[3]; b[3] = t; t = b[1]; b[1] = b[2]; b[2] = t;
}
static void swapf(float *a, long n) { long i; if (!big_endian()) return; for (i = 0; i < n; i++) swap4(&a[i]); }
static void swap_scales(QuantizedTensor *qt, int n, int size_each) {
    int i; if (!big_endian()) return;
    for (i = 0; i < n; i++) swapf(qt[i].s, size_each / GS);
}

/* Precompute the RoPE rotation table once at init. The expressions are
 * copied verbatim from runq.c's per-token loop, so the table entries are
 * bit-identical to what the reference computes on the fly. Costs
 * seq_len * head_size/2 * 2 floats of RAM (256*8*2*4 = 16K at head 16). */
static int build_rope(Config *p) {
    int hs = p->dim / p->n_heads, half = hs >> 1, k;
    long pos, n = (long)p->seq_len * half;
    float *freq;
    gRopeCos = (float *)malloc(n * sizeof(float));
    gRopeSin = (float *)malloc(n * sizeof(float));
    freq = (float *)malloc((half > 0 ? half : 1) * sizeof(float));
    if (!gRopeCos || !gRopeSin || !freq) return -1;
    /* freq depends only on the head dim (hd = 2k), NOT on pos: compute the
     * expensive powf once per k (4 calls here) instead of seq_len*half. The
     * values are bit-identical to the per-token reference (hd = 2k). */
    for (k = 0; k < half; k++)
        freq[k] = 1.0f / powf(10000.0f, (2 * k) / (float)hs);
    for (pos = 0; pos < p->seq_len; pos++) {
        for (k = 0; k < half; k++) {
            float val = pos * freq[k];
            gRopeCos[pos * half + k] = cosf(val);
            gRopeSin[pos * half + k] = sinf(val);
        }
    }
    free(freq);
    return 0;
}

/* Map weights straight out of the in-RAM checkpoint buffer. Same as runq.c's
 * memory_map_weights but WITHOUT building a full dequantized token table --
 * forward() dequantizes the one needed row per step instead (saves vocab*dim
 * floats of RAM). */
static void map_weights(TransformerWeights *w, Config *p, void *ptr, int shared_classifier) {
    int head_size = p->dim / p->n_heads;
    float *fptr = (float *)ptr;
    w->rms_att_weight = fptr; fptr += p->n_layers * p->dim;
    w->rms_ffn_weight = fptr; fptr += p->n_layers * p->dim;
    w->rms_final_weight = fptr; fptr += p->dim;
    ptr = (void *)fptr;
    w->q_tokens = init_quantized_tensors(&ptr, 1, p->vocab_size * p->dim);
    w->token_embedding_table = 0L;              /* dequantized on the fly */
    w->wq = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_heads * head_size));
    w->wk = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_kv_heads * head_size));
    w->wv = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_kv_heads * head_size));
    w->wo = init_quantized_tensors(&ptr, p->n_layers, (p->n_heads * head_size) * p->dim);
    w->w1 = init_quantized_tensors(&ptr, p->n_layers, p->dim * p->hidden_dim);
    w->w2 = init_quantized_tensors(&ptr, p->n_layers, p->hidden_dim * p->dim);
    w->w3 = init_quantized_tensors(&ptr, p->n_layers, p->dim * p->hidden_dim);
    w->wcls = shared_classifier ? w->q_tokens
              : init_quantized_tensors(&ptr, 1, p->dim * p->vocab_size);
}

/* v2 checkpoint header: [magic u32][version i32][Config 7*i32][shared u8][GS i32]
 * padded to 256 bytes, then the weights. All scalars little-endian. */
static int load_model_mem(Transformer *t, const void *data, long len) {
    const unsigned char *b = (const unsigned char *)data;
    Config *p = &t->config;
    int cfg = (int)sizeof(Config);      /* 28 */
    uint8_t shared; int hs, L;
    if (len < 256) return -1;
    if (rd32(b) != 0x616b3432u) return -1;          /* magic "ak42" */
    if ((int)rd32(b + 4) != 2) return -1;           /* version 2 */
    p->dim        = (int)rd32(b + 8);
    p->hidden_dim = (int)rd32(b + 12);
    p->n_layers   = (int)rd32(b + 16);
    p->n_heads    = (int)rd32(b + 20);
    p->n_kv_heads = (int)rd32(b + 24);
    p->vocab_size = (int)rd32(b + 28);
    p->seq_len    = (int)rd32(b + 32);
    shared = b[8 + cfg];                             /* b[36] */
    GS = (int)rd32(b + 8 + cfg + 1);                 /* b[37..40] */
    if (GS <= 0 || (GS & 7)) return -1;              /* unrolled matmul needs GS % 8 == 0 */
    map_weights(&t->weights, p, (void *)(b + 256), shared);

    /* On big-endian (the Mac) the fp32 regions are byte-swapped in place to
     * native order. No-op on little-endian. */
    hs = p->dim / p->n_heads; L = p->n_layers;
    swapf(t->weights.rms_att_weight,   (long)L * p->dim);
    swapf(t->weights.rms_ffn_weight,   (long)L * p->dim);
    swapf(t->weights.rms_final_weight, p->dim);
    swap_scales(t->weights.q_tokens, 1, p->vocab_size * p->dim);
    swap_scales(t->weights.wq, L, p->dim * (p->n_heads * hs));
    swap_scales(t->weights.wk, L, p->dim * (p->n_kv_heads * hs));
    swap_scales(t->weights.wv, L, p->dim * (p->n_kv_heads * hs));
    swap_scales(t->weights.wo, L, (p->n_heads * hs) * p->dim);
    swap_scales(t->weights.w1, L, p->dim * p->hidden_dim);
    swap_scales(t->weights.w2, L, p->hidden_dim * p->dim);
    swap_scales(t->weights.w3, L, p->dim * p->hidden_dim);
    if (t->weights.wcls != t->weights.q_tokens)
        swap_scales(t->weights.wcls, 1, p->dim * p->vocab_size);
    return 0;
}

void rmsnorm(float* o, float* x, float* weight, int size) {
    // calculate sum of squares
    float ss = 0.0f;
    for (int j = 0; j < size; j++) {
        ss += x[j] * x[j];
    }
    ss /= size;
    ss += 1e-5f;
    ss = 1.0f / sqrtf(ss);
    // normalize and scale
    for (int j = 0; j < size; j++) {
        o[j] = weight[j] * (ss * x[j]);
    }
}

void softmax(float* x, int size) {
    // find max value (for numerical stability)
    float max_val = x[0];
    for (int i = 1; i < size; i++) {
        if (x[i] > max_val) {
            max_val = x[i];
        }
    }
    // exp and sum
    float sum = 0.0f;
    for (int i = 0; i < size; i++) {
        x[i] = expf(x[i] - max_val);
        sum += x[i];
    }
    // normalize
    for (int i = 0; i < size; i++) {
        x[i] /= sum;
    }
}

void matmul(float* xout, QuantizedTensor *x, QuantizedTensor *w, int n, int d) {
    /* W (d,n) @ x (n,) -> xout (d,) -- THE hot loop (~90% of a token).
     * int8 x int8 products come from gMulLUT (a 128KB table) instead of the
     * 68000's slow MULS.W. The products are IDENTICAL, so the output is
     * byte-for-byte the same as the reference -- this is a pure speedup, not
     * an approximation. x[k] is pre-shifted into the high index byte once per
     * matmul (x8buf) so the inner MAC is just: table[x8 | w]. Unrolled 8x
     * (GS % 8 == 0, checked at load). No divide in the loop (both scale arrays
     * walked with pointers). Same per-group float summation order. */
    int i, j, k;
    static unsigned short x8buf[512];   /* ((uint8)x[k]) << 8, reused per row */
    const int8_t *wp  = w->q;
    const float  *wsp = w->s;
    for (k = 0; k < n; k++)
        x8buf[k] = (unsigned short)(((unsigned)(unsigned char)x->q[k]) << 8);
    for (i = 0; i < d; i++) {
        float val = 0.0f;
        const float          *xsp = x->s;
        const unsigned short *x8  = x8buf;
        for (j = 0; j <= n - GS; j += GS) {
            int32_t ival = 0;
            for (k = 0; k < GS; k += 8) {
                ival += gMulLUT[x8[0] | (unsigned char)wp[0]];
                ival += gMulLUT[x8[1] | (unsigned char)wp[1]];
                ival += gMulLUT[x8[2] | (unsigned char)wp[2]];
                ival += gMulLUT[x8[3] | (unsigned char)wp[3]];
                ival += gMulLUT[x8[4] | (unsigned char)wp[4]];
                ival += gMulLUT[x8[5] | (unsigned char)wp[5]];
                ival += gMulLUT[x8[6] | (unsigned char)wp[6]];
                ival += gMulLUT[x8[7] | (unsigned char)wp[7]];
                x8 += 8; wp += 8;
            }
            val += ((float) ival) * (*wsp++) * (*xsp++);
        }
        xout[i] = val;
    }
}

float* forward(Transformer* transformer, int token, int pos) {

    // a few convenience variables
    Config* p = &transformer->config;
    TransformerWeights* w = &transformer->weights;
    RunState* s = &transformer->state;
    float *x = s->x;
    int dim = p->dim;
    int kv_dim = (p->dim * p->n_kv_heads) / p->n_heads;
    int kv_mul = p->n_heads / p->n_kv_heads; // integer multiplier of the kv sharing in multiquery
    int hidden_dim =  p->hidden_dim;
    int head_size = dim / p->n_heads;

    // copy the token embedding into x
    { QuantizedTensor *qt = w->q_tokens; int _i;
      for (_i = 0; _i < dim; _i++)
          x[_i] = ((float)qt->q[token*dim + _i]) * qt->s[(token*dim + _i) / GS]; }

    // forward all the layers
    for(int l = 0; l < p->n_layers; l++) {

        // attention rmsnorm
        rmsnorm(s->xb, x, w->rms_att_weight + l*dim, dim);

        // qkv matmuls for this position
        quantize(&s->xq, s->xb, dim);
        matmul(s->q, &s->xq, w->wq + l, dim, dim);
        matmul(s->k, &s->xq, w->wk + l, dim, kv_dim);
        matmul(s->v, &s->xq, w->wv + l, dim, kv_dim);

        // RoPE relative positional encoding: complex-valued rotate q and k in each head
        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float fcr = gRopeCos[pos * (head_size >> 1) + (head_dim >> 1)];
            float fci = gRopeSin[pos * (head_size >> 1) + (head_dim >> 1)];
            int rotn = i < kv_dim ? 2 : 1; // how many vectors? 2 = q & k, 1 = q only
            for (int v = 0; v < rotn; v++) {
                float* vec = v == 0 ? s->q : s->k; // the vector to rotate (query or key)
                float v0 = vec[i];
                float v1 = vec[i+1];
                vec[i]   = v0 * fcr - v1 * fci;
                vec[i+1] = v0 * fci + v1 * fcr;
            }
        }

        // save key,value at this time step (pos) to our kv cache
        int loff = l * p->seq_len * kv_dim; // kv cache layer offset for convenience
        float* key_cache_row = s->key_cache + loff + pos * kv_dim;
        float* value_cache_row = s->value_cache + loff + pos * kv_dim;
        memcpy(key_cache_row, s->k, kv_dim * sizeof(*key_cache_row));
        memcpy(value_cache_row, s->v, kv_dim * sizeof(*value_cache_row));

        // multihead attention. iterate over all heads
        int h;
        for (h = 0; h < p->n_heads; h++) {
            // get the query vector for this head
            float* q = s->q + h * head_size;
            // attention scores for this head
            float* att = s->att + h * p->seq_len;
            // iterate over all timesteps, including the current one
            for (int t = 0; t <= pos; t++) {
                // get the key vector for this head and at this timestep
                float* k = s->key_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // calculate the attention score as the dot product of q and k
                float score = 0.0f;
                for (int i = 0; i < head_size; i++) {
                    score += q[i] * k[i];
                }
                score /= gAttnScale;      /* == sqrtf(head_size), hoisted */
                // save the score to the attention buffer
                att[t] = score;
            }

            // softmax the scores to get attention weights, from 0..pos inclusively
            softmax(att, pos + 1);

            // weighted sum of the values, store back into xb
            float* xb = s->xb + h * head_size;
            memset(xb, 0, head_size * sizeof(float));
            for (int t = 0; t <= pos; t++) {
                // get the value vector for this head and at this timestep
                float* v = s->value_cache + loff + t * kv_dim + (h / kv_mul) * head_size;
                // get the attention weight for this timestep
                float a = att[t];
                // accumulate the weighted value into xb
                for (int i = 0; i < head_size; i++) {
                    xb[i] += a * v[i];
                }
            }
        }

        // final matmul to get the output of the attention
        quantize(&s->xq, s->xb, dim);
        matmul(s->xb2, &s->xq, w->wo + l, dim, dim);

        // residual connection back into x
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb2[i];
        }

        // ffn rmsnorm
        rmsnorm(s->xb, x, w->rms_ffn_weight + l*dim, dim);

        // Now for FFN in PyTorch we have: self.w2(F.silu(self.w1(x)) * self.w3(x))
        // first calculate self.w1(x) and self.w3(x)
        quantize(&s->xq, s->xb, dim);
        matmul(s->hb, &s->xq, w->w1 + l, dim, hidden_dim);
        matmul(s->hb2, &s->xq, w->w3 + l, dim, hidden_dim);

        // SwiGLU non-linearity
        for (int i = 0; i < hidden_dim; i++) {
            float val = s->hb[i];
            // silu(x)=x*σ(x), where σ(x) is the logistic sigmoid
            val *= (1.0f / (1.0f + expf(-val)));
            // elementwise multiply with w3(x)
            val *= s->hb2[i];
            s->hb[i] = val;
        }

        // final matmul to get the output of the ffn
        quantize(&s->hq, s->hb, hidden_dim);
        matmul(s->xb, &s->hq, w->w2 + l, hidden_dim, dim);

        // residual connection
        for (int i = 0; i < dim; i++) {
            x[i] += s->xb[i];
        }
    }

    // during prompt prefill the logits are never read: skip the final
    // rmsnorm + the dim x vocab classifier matmul (~30% of a forward pass)
    if (!gWantLogits) return s->logits;

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);

    // classifier into logits
    quantize(&s->xq, x, dim);
    matmul(s->logits, &s->xq, w->wcls, dim, p->vocab_size);
    return s->logits;
}

typedef struct {
    char *str;
    int id;
} TokenIndex;

typedef struct {
    char** vocab;
    float* vocab_scores;
    TokenIndex *sorted_vocab;
    int vocab_size;
    unsigned int max_token_length;
    unsigned char byte_pieces[512]; // stores all single-byte strings
} Tokenizer;

int compare_tokens(const void *a, const void *b) {
    return strcmp(((TokenIndex*)a)->str, ((TokenIndex*)b)->str);
}

/* Tokenizer parsed from an in-RAM buffer (was fopen/fread).
 * format: [max_token_length i32] then per token: [score f32][len i32][bytes].
 *
 * The vocab strings go in ONE block, not vocab_size separate mallocs. On the
 * 68000 Mac, ~2048 small NewPtr calls after the big KV-cache alloc thrash the
 * Memory Manager's free list (O(n^2)) -- that was ~60s of the startup. One
 * allocation makes the load near-instant. gTokBlob is freed in free_tokenizer. */
static char *gTokBlob = 0L;
static void build_tokenizer_mem(Tokenizer *t, const void *data, int vocab_size) {
    const unsigned char *b = (const unsigned char *)data;
    long off, total; int i, slen; char *dst;
    t->vocab_size = vocab_size;
    t->vocab = (char **)malloc(vocab_size * sizeof(char *));
    t->vocab_scores = (float *)malloc(vocab_size * sizeof(float));
    t->sorted_vocab = 0L;
    for (i = 0; i < 256; i++) { t->byte_pieces[i*2] = (unsigned char)i; t->byte_pieces[i*2+1] = '\0'; }
    t->max_token_length = rd32(b);                   /* little-endian */
    /* pass 1: total bytes for all strings (+1 NUL each) */
    off = 4; total = 0;
    for (i = 0; i < vocab_size; i++) {
        off += 4;                                    /* score */
        slen = (int)rd32(b + off); off += 4;
        total += (long)slen + 1;
        off += slen;
    }
    gTokBlob = (char *)malloc(total > 0 ? total : 1);
    /* pass 2: copy each string into the blob; vocab[i] points into it */
    off = 4; dst = gTokBlob;
    for (i = 0; i < vocab_size; i++) {
        t->vocab_scores[i] = rdf(b + off); off += 4;
        slen = (int)rd32(b + off);         off += 4;
        t->vocab[i] = dst;
        memcpy(dst, b + off, slen); dst[slen] = '\0';
        dst += slen + 1; off += slen;
    }
}

void free_tokenizer(Tokenizer* t) {
    free(gTokBlob); gTokBlob = 0L;    /* strings are one block now, not per-token */
    free(t->vocab);
    free(t->vocab_scores);
    free(t->sorted_vocab);
}

char* decode(Tokenizer* t, int prev_token, int token) {
    char *piece = t->vocab[token];
    // following BOS (1) token, sentencepiece decoder strips any leading whitespace (see PR #89)
    if (prev_token == 1 && piece[0] == ' ') { piece++; }
    // careful, some tokens designate raw bytes, and look like e.g. '<0x01>'
    // parse this and convert and return the actual byte
    unsigned char byte_val;
    if (piece[0]=='<' && piece[1]=='0' && piece[2]=='x' && piece[5]=='>' && piece[6]=='\0') {
        int _hi = piece[3], _lo = piece[4];
        _hi = (_hi<='9') ? _hi-'0' : ((_hi|0x20)-'a'+10);
        _lo = (_lo<='9') ? _lo-'0' : ((_lo|0x20)-'a'+10);
        if (_hi>=0 && _hi<16 && _lo>=0 && _lo<16) {
            byte_val = (unsigned char)(_hi*16 + _lo);
            piece = (char*)t->byte_pieces + byte_val * 2;
        }
    }
    return piece;
}

void safe_printf(char *piece) {
    // piece might be a raw byte token, and we only want to print printable chars or whitespace
    // because some of the other bytes can be various control codes, backspace, etc.
    if (piece == NULL) { return; }
    if (piece[0] == '\0') { return; }
    if (piece[1] == '\0') {
        unsigned char byte_val = piece[0];
        if (!(isprint(byte_val) || isspace(byte_val))) {
            return; // bad byte, don't print it
        }
    }
    printf("%s", piece);
}

int str_lookup(char *str, TokenIndex *sorted_vocab, int vocab_size) {
    // efficiently find the perfect match for str in vocab, return its index or -1 if not found
    TokenIndex tok = { .str = str }; // acts as the key to search for
    TokenIndex *res = bsearch(&tok, sorted_vocab, vocab_size, sizeof(TokenIndex), compare_tokens);
    return res != NULL ? res->id : -1;
}

void encode(Tokenizer* t, char *text, int8_t bos, int8_t eos, int *tokens, int *n_tokens) {
    // encode the string text (input) into an upper-bound preallocated tokens[] array
    // bos != 0 means prepend the BOS token (=1), eos != 0 means append the EOS token (=2)
    if (text == NULL) { fprintf(stderr, "cannot encode NULL text\n"); exit(EXIT_FAILURE); }

    if (t->sorted_vocab == NULL) {
        // lazily malloc and sort the vocabulary
        t->sorted_vocab = malloc(t->vocab_size * sizeof(TokenIndex));
        for (int i = 0; i < t->vocab_size; i++) {
            t->sorted_vocab[i].str = t->vocab[i];
            t->sorted_vocab[i].id = i;
        }
        qsort(t->sorted_vocab, t->vocab_size, sizeof(TokenIndex), compare_tokens);
    }

    // create a temporary buffer that will store merge candidates of always two consecutive tokens
    // *2 for concat, +1 for null terminator +2 for UTF8 (in case max_token_length is 1)
    char* str_buffer = malloc((t->max_token_length*2 +1 +2) * sizeof(char));
    size_t str_len = 0;

    // start at 0 tokens
    *n_tokens = 0;

    // add optional BOS (=1) token, if desired
    if (bos) tokens[(*n_tokens)++] = 1;

    // add_dummy_prefix is true by default
    // so prepend a dummy prefix token to the input string, but only if text != ""
    // TODO: pretty sure this isn't correct in the general case but I don't have the
    // energy to read more of the sentencepiece code to figure out what it's doing
    if (text[0] != '\0') {
        int dummy_prefix = str_lookup(" ", t->sorted_vocab, t->vocab_size);
        tokens[(*n_tokens)++] = dummy_prefix;
    }

    // Okay UTF-8 time. This will get messy. Here is the reference from Wikipedia:
    // Code point ↔ UTF-8 conversion
    // First code point	Last code point	Byte 1	Byte 2	Byte 3	Byte 4
    // U+0000	U+007F	    0xxxxxxx
    // U+0080	U+07FF	    110xxxxx	10xxxxxx
    // U+0800	U+FFFF	    1110xxxx	10xxxxxx	10xxxxxx
    // U+10000	U+10FFFF    11110xxx	10xxxxxx	10xxxxxx	10xxxxxx

    // process the raw (UTF-8) byte sequence of the input string
    for (char *c = text; *c != '\0'; c++) {

        // reset buffer if the current byte is ASCII or a leading byte
        // 0xC0 is 11000000, so (*c & 0xC0) keeps the first 2 bits and zeros the rest
        // 0x80 is 10000000
        // in UTF-8, all continuation bytes start with "10" in first two bits
        // so in English this is: "if this byte is not a continuation byte"
        if ((*c & 0xC0) != 0x80) {
            // this byte must be either a leading byte (11...) or an ASCII char (0x...)
            // => reset our location, as we're starting a new UTF-8 codepoint
            str_len = 0;
        }

        // append the current byte to the buffer
        str_buffer[str_len++] = *c; // ++ is post-increment, incremented after this line
        str_buffer[str_len] = '\0';

        // while the next character is a continuation byte, continue appending
        // but if there are too many of them, just stop to avoid overruning str_buffer size.
        if ((*(c+1) & 0xC0) == 0x80 && str_len < 4) {
            continue;
        }

        // ok c+1 is not a continuation byte, so we've read in a full codepoint
        int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);

        if (id != -1) {
            // we found this codepoint in vocab, add it as a token
            tokens[(*n_tokens)++] = id;
        } else {
            // byte_fallback encoding: just encode each byte as a token
            // +3 is here because the first 3 vocab elements are <unk>, <s>, </s>
            // so the individual bytes only start at index 3
            for (int i=0; i < str_len; i++) {
                tokens[(*n_tokens)++] = (unsigned char)str_buffer[i] + 3;
            }
        }
        str_len = 0; // protect against a sequence of stray UTF8 continuation bytes
    }

    // merge the best consecutive pair each iteration, according the scores in vocab_scores
    while (1) {
        float best_score = -1e10;
        int best_id = -1;
        int best_idx = -1;

        for (int i=0; i < (*n_tokens-1); i++) {
            // check if we can merge the pair (tokens[i], tokens[i+1])
            sprintf(str_buffer, "%s%s", t->vocab[tokens[i]], t->vocab[tokens[i+1]]);
            int id = str_lookup(str_buffer, t->sorted_vocab, t->vocab_size);
            if (id != -1 && t->vocab_scores[id] > best_score) {
                // this merge pair exists in vocab! record its score and position
                best_score = t->vocab_scores[id];
                best_id = id;
                best_idx = i;
            }
        }

        if (best_idx == -1) {
            break; // we couldn't find any more pairs to merge, so we're done
        }

        // merge the consecutive pair (best_idx, best_idx+1) into new token best_id
        tokens[best_idx] = best_id;
        // delete token at position best_idx+1, shift the entire sequence back 1
        for (int i = best_idx+1; i < (*n_tokens-1); i++) {
            tokens[i] = tokens[i+1];
        }
        (*n_tokens)--; // token length decreased
    }

    // add optional EOS (=2) token, if desired
    if (eos) tokens[(*n_tokens)++] = 2;

    free(str_buffer);
}

// ----------------------------------------------------------------------------
// The Sampler, which takes logits and returns a sampled token
// sampling can be done in a few ways: greedy argmax, sampling, top-p sampling

typedef struct {
    float prob;
    int index;
} ProbIndex; // struct used when sorting probabilities during top-p sampling

typedef struct {
    int vocab_size;
    ProbIndex* probindex; // buffer used in top-p sampling
    float temperature;
    float topp;
    unsigned long long rng_state;
} Sampler;

int sample_argmax(float* probabilities, int n) {
    // return the index that has the highest probability
    int max_i = 0;
    float max_p = probabilities[0];
    for (int i = 1; i < n; i++) {
        if (probabilities[i] > max_p) {
            max_i = i;
            max_p = probabilities[i];
        }
    }
    return max_i;
}

int sample_mult(float* probabilities, int n, float coin) {
    // sample index from probabilities (they must sum to 1!)
    // coin is a random number in [0, 1), usually from random_f32()
    float cdf = 0.0f;
    for (int i = 0; i < n; i++) {
        cdf += probabilities[i];
        if (coin < cdf) {
            return i;
        }
    }
    return n - 1; // in case of rounding errors
}

int compare(const void* a, const void* b) {
    ProbIndex* a_ = (ProbIndex*) a;
    ProbIndex* b_ = (ProbIndex*) b;
    if (a_->prob > b_->prob) return -1;
    if (a_->prob < b_->prob) return 1;
    return 0;
}

int sample_topp(float* probabilities, int n, float topp, ProbIndex* probindex, float coin) {
    // top-p sampling (or "nucleus sampling") samples from the smallest set of
    // tokens that exceed probability topp. This way we never sample tokens that
    // have very low probabilities and are less likely to go "off the rails".
    // coin is a random number in [0, 1), usually from random_f32()

    int n0 = 0;
    // quicksort indices in descending order of probabilities
    // values smaller than (1 - topp) / (n - 1) cannot be part of the result
    // so for efficiency we crop these out as candidates before sorting
    const float cutoff = (1.0f - topp) / (n - 1);
    for (int i = 0; i < n; i++) {
        if (probabilities[i] >= cutoff) {
            probindex[n0].index = i;
            probindex[n0].prob = probabilities[i];
            n0++;
        }
    }
    qsort(probindex, n0, sizeof(ProbIndex), compare);

    // truncate the list where cumulative probability exceeds topp
    float cumulative_prob = 0.0f;
    int last_idx = n0 - 1; // in case of rounding errors consider all elements
    for (int i = 0; i < n0; i++) {
        cumulative_prob += probindex[i].prob;
        if (cumulative_prob > topp) {
            last_idx = i;
            break; // we've exceeded topp by including last_idx
        }
    }

    // sample from the truncated list
    float r = coin * cumulative_prob;
    float cdf = 0.0f;
    for (int i = 0; i <= last_idx; i++) {
        cdf += probindex[i].prob;
        if (r < cdf) {
            return probindex[i].index;
        }
    }
    return probindex[last_idx].index; // in case of rounding errors
}

void build_sampler(Sampler* sampler, int vocab_size, float temperature, float topp, unsigned long long rng_seed) {
    sampler->vocab_size = vocab_size;
    sampler->temperature = temperature;
    sampler->topp = topp;
    sampler->rng_state = rng_seed;
    // buffer only used with nucleus sampling; may not need but it's ~small
    sampler->probindex = malloc(sampler->vocab_size * sizeof(ProbIndex));
}

void free_sampler(Sampler* sampler) {
    free(sampler->probindex);
}

unsigned int random_u32(unsigned long long *state) {
    // xorshift rng: https://en.wikipedia.org/wiki/Xorshift#xorshift.2A
    *state ^= *state >> 12;
    *state ^= *state << 25;
    *state ^= *state >> 27;
    return (*state * 0x2545F4914F6CDD1Dull) >> 32;
}
float random_f32(unsigned long long *state) { // random float32 in [0,1)
    return (random_u32(state) >> 8) / 16777216.0f;
}

#define GPT_TOPK 40

static int sample_topk(Sampler *sampler, float *logits) {
    /* top-k sampling built for the 68000: one early-out pass selects the k
     * highest logits (no softmax over the whole vocab, no qsort -- those cost
     * seconds per token in software float), then a temperature softmax over
     * just those k and one draw. */
    ProbIndex *pi = sampler->probindex;
    int n = sampler->vocab_size, k = GPT_TOPK;
    int i, j, cnt = 0, mini = 0;
    float coin, maxv, sum, r, cdf;
    if (k > n) k = n;
    for (i = 0; i < n; i++) {
        float v = logits[i];
        if (cnt < k) {
            pi[cnt].prob = v; pi[cnt].index = i;
            if (++cnt == k) {
                mini = 0;
                for (j = 1; j < k; j++) if (pi[j].prob < pi[mini].prob) mini = j;
            }
        } else if (v > pi[mini].prob) {
            pi[mini].prob = v; pi[mini].index = i;
            mini = 0;
            for (j = 1; j < k; j++) if (pi[j].prob < pi[mini].prob) mini = j;
        }
    }
    maxv = pi[0].prob;
    for (i = 1; i < cnt; i++) if (pi[i].prob > maxv) maxv = pi[i].prob;
    sum = 0.0f;
    for (i = 0; i < cnt; i++) {
        pi[i].prob = expf((pi[i].prob - maxv) / sampler->temperature);
        sum += pi[i].prob;
    }
    coin = random_f32(&sampler->rng_state);
    r = coin * sum;
    cdf = 0.0f;
    for (i = 0; i < cnt; i++) {
        cdf += pi[i].prob;
        if (r < cdf) return pi[i].index;
    }
    return pi[cnt - 1].index;
}

int sample(Sampler* sampler, float* logits) {
    if (sampler->temperature == 0.0f)
        return sample_argmax(logits, sampler->vocab_size);   /* greedy: exact */
    return sample_topk(sampler, logits);
}


/* ---------------------------------------------------------------------------
 * Public engine API (replaces runq.c's generate/chat/main)
 * ------------------------------------------------------------------------- */
static Transformer gT;
static Tokenizer   gTok;
static Sampler     gSmp;
static int         gReady = 0;

int GptInitMem(const void *modelData, long modelLen,
               const void *tokData, long tokLen,
               float temperature, float topp, unsigned long seed) {
    (void)tokLen;
    if (gReady) GptShutdown();
    PROG(1);
    if (load_model_mem(&gT, modelData, modelLen) != 0) return -1;
    if (build_mul_lut() != 0) return -1;      /* int8xint8 product table */
    PROG(2);
    if (build_rope(&gT.config) != 0) return -1;
    gAttnScale = sqrtf(gT.config.dim / gT.config.n_heads);
    PROG(4);
    malloc_run_state(&gT.state, &gT.config);
    PROG(5);
    build_tokenizer_mem(&gTok, tokData, gT.config.vocab_size);
    PROG(6);
    build_sampler(&gSmp, gT.config.vocab_size, temperature, topp,
                  (unsigned long long)seed);
    PROG(7);
    gReady = 1;
    return 0;
}

int  GptReady(void)  { return gReady; }
int  GptSeqLen(void) { return gReady ? gT.config.seq_len : 0; }

/* DEBUG: raw IEEE bits of a few loaded weights (to compare host vs big-endian
 * Mac) and the argmax token predicted from BOS. */
unsigned long GptDbgBits(int i) {
    float f = 0.0f; uint32_t u;
    if (!gReady) return 0;
    if      (i == 0) f = gT.weights.rms_att_weight[0];
    else if (i == 1) f = gT.weights.q_tokens[0].s[0];
    else if (i == 2) f = gT.weights.wq[0].s[0];
    else if (i == 3) f = gT.weights.w1[0].s[0];
    memcpy(&u, &f, 4);
    return (unsigned long)u;
}
int GptDbgFirstTok(void) {
    float *logits;
    if (!gReady) return -1;
    gWantLogits = 1;
    logits = forward(&gT, 1, 0);      /* BOS at position 0 */
    return sample_argmax(logits, gT.config.vocab_size);
}

/* DEBUG: encode `prompt`, run the prompt through, return promptLen, first two
 * token ids, and the greedy first generated token. For host-vs-Mac diffing. */
void GptDbgProbe(const char *prompt, int *pLen, int *pT0, int *pT1, int *pFirst) {
    int ptoks[64], n = 0, pos, token;
    *pLen = *pT0 = *pT1 = *pFirst = -1;
    if (!gReady) return;
    encode(&gTok, (char *)prompt, 1, 0, ptoks, &n);
    *pLen = n;
    if (n > 0) *pT0 = ptoks[0];
    if (n > 1) *pT1 = ptoks[1];
    token = ptoks[0];
    for (pos = 0; pos < n; pos++) {
        float *logits;
        gWantLogits = (pos == n - 1);
        logits = forward(&gT, token, pos);
        if (pos < n - 1) token = ptoks[pos + 1];
        else *pFirst = sample_argmax(logits, gT.config.vocab_size);
    }
    gWantLogits = 1;
}

void GptShutdown(void) {
    if (!gReady) return;
    free_sampler(&gSmp);
    free_tokenizer(&gTok);
    /* free the QuantizedTensor arrays (the .q/.s point into the resource, which
     * the Resource Manager owns -- don't free those). */
    free(gT.weights.q_tokens);
    free(gT.weights.wq); free(gT.weights.wk); free(gT.weights.wv); free(gT.weights.wo);
    free(gT.weights.w1); free(gT.weights.w2); free(gT.weights.w3);
    if (gT.weights.wcls != gT.weights.q_tokens) free(gT.weights.wcls);
    free_run_state(&gT.state);
    if (gRopeCos) { free(gRopeCos); gRopeCos = 0L; }
    if (gRopeSin) { free(gRopeSin); gRopeSin = 0L; }
    if (gMulLUT)  { free(gMulLUT);  gMulLUT  = 0L; }
    gWantLogits = 1;
    gReady = 0;
}

/* Generate a continuation of `prompt`, streaming decoded pieces to emit().
 * tick (may be NULL) is called after every forward pass:
 *   phase 0 = reading the prompt   (done/total = prompt positions)
 *   phase 1 = generating the reply (done/total = new tokens)
 * Return 0 from tick to stop cleanly (user cancel / app decides it has
 * enough). The app uses tick to pump its event loop, so the Mac stays
 * responsive across a multi-minute reply. */
void GptGenerate(const char *prompt, int maxNewTokens,
                 GptEmit emit, GptTick tick, void *ctx) {
    int seqcap, plen, promptLen, token, pos, total, next, generated;
    int *ptoks;
    const char *p;
    if (!gReady || emit == 0L) return;
    if (prompt == 0L) prompt = "";
    seqcap = gT.config.seq_len;

    plen = 0; p = prompt; while (p[plen]) plen++;
    ptoks = (int *)malloc((size_t)(plen + 3) * sizeof(int));
    if (!ptoks) return;
    promptLen = 0;
    encode(&gTok, (char *)prompt, 1, 0, ptoks, &promptLen);
    if (promptLen < 1) { free(ptoks); return; }
    if (promptLen > seqcap - 8) promptLen = seqcap - 8;  /* leave room to reply */

    token = ptoks[0];
    pos = 0;
    generated = 0;
    total = promptLen + maxNewTokens;
    if (total > seqcap) total = seqcap;

    while (pos < total) {
        int prefill = (pos < promptLen - 1);
        float *logits;
        gWantLogits = !prefill;
        logits = forward(&gT, token, pos);
        if (prefill) next = ptoks[pos + 1];
        else         next = sample(&gSmp, logits);
        pos++;
        if (next == 1) break;                    /* BOS: the post ended */
        if (pos >= promptLen) {
            char *piece = decode(&gTok, token, next);
            if (piece && piece[0] != '\0') emit(piece, ctx);
            generated++;
        }
        if (tick) {
            int go = prefill ? tick(0, pos, promptLen, ctx)
                             : tick(1, generated, maxNewTokens, ctx);
            if (!go) break;
        }
        token = next;
    }
    gWantLogits = 1;
    free(ptoks);
}
