#!/usr/bin/env python3
"""Assemble gpt.c from llama2.c/runq.c (int8 quantized engine), v2.

Reuses runq.c's numeric code verbatim (quantize/dequantize/forward/tokenizer)
and swaps the Unix/CLI parts for the Mac:
  - load from an in-RAM buffer (an embedded resource) instead of mmap'ing a file
  - dequantize the token-embedding ROW on the fly in forward() instead of holding
    a full dequantized fp32 table (~500KB saved) -- important on the 4MB Plus
  - printf output -> a streaming callback; no CLI main/chat

v2 (2026-07-04) -- the 68000 speed pass. Every change below is bit-identical
to the reference numerics (same float ops, same order) EXCEPT the sampler at
temperature > 0 (top-k replaces top-p; temp 0 argmax is unchanged, which is
what the host equivalence test runs):
  1. matmul: int8 products via the gcc mulhisi3 idiom so the 68000 uses its
     native 16x16 muls.w instead of a __mulsi3 library call; inner loop
     unrolled 8x. Same products, same per-group summation order.
  2. RoPE: cos/sin precomputed once at init into tables (identical
     expressions), killing ~600 soft-float powf/cosf/sinf calls per token.
  3. attention: sqrtf(head_size) hoisted to init (gAttnScale).
  4. prefill: while processing the prompt the logits are never read, so the
     final rmsnorm + dim x vocab classifier matmul are skipped (~30%/token).
  5. sampler: top-k (k=40) with softmax over just the k survivors -- replaces
     softmax-over-vocab + qsort. temp==0 still routes to sample_argmax.
  6. GptGenerate gains a tick callback: per-position progress + abort, so the
     app can pump its event loop and cancel mid-reply.
"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
RUN = os.path.join(HERE, "..", "llama2.c", "runq.c")
OUT = os.path.join(HERE, "gpt.c")

lines = open(RUN).read().split("\n")
def slc(a, b):  # 1-indexed inclusive
    return "\n".join(lines[a-1:b])

header = '''/*
 * gpt.c -- int8 llama2 inference for THE ORACLE (Mac Plus / Retro68), v2.
 * GENERATED by make_gpt.py from ../llama2.c/runq.c. Do not hand-edit.
 * Loads weights from an in-RAM buffer (embedded 'MODL'/'TOKN' resources), so
 * there is no file I/O and no big single allocation -- fits the 4MB Plus.
 * v2: 68000 speed pass (muls.w matmul, RoPE tables, prefill classifier skip,
 * top-k sampler, tick/abort callback). See make_gpt.py.
 */
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include "gpt.h"
'''

# GS global + structs + malloc/free run state (verbatim; ssize_t -> long).
part_structs = slc(19, 134).replace("ssize_t", "long")

# dequantize + quantize + init_quantized_tensors (verbatim).
part_quant = slc(139, 187)

# our weight mapper + memory loader (replaces runq's mmap read_checkpoint).
# NOTE endianness: llama2.c checkpoints are LITTLE-endian; the 68000 Mac is
# BIG-endian. Header/tokenizer scalars are read little-endian explicitly (rd32/
# rdf, correct on any host). The fp32 weight/scale regions are accessed in place
# as native floats, so they are byte-swapped in place once at load -- but only on
# a big-endian host (no-op on the little-endian dev machine, so the host test
# still passes).
part_loader = '''
/* optional progress hook (for the app's loading UI / remote diagnosis) */
void (*gGptProgress)(int step) = 0;
#define PROG(n) do { if (gGptProgress) gGptProgress(n); } while (0)

/* generation-time knobs & tables (v2 engine) */
int gWantLogits = 1;              /* 0 during prompt prefill: skip classifier */
static float gAttnScale = 1.0f;   /* sqrtf(head_size), hoisted out of attention */
static float *gRopeCos = 0L, *gRopeSin = 0L;   /* [seq_len][head_size/2] */

/* int8 x int8 product table (v3 speed): the 68000's MULS.W is ~50 cycles; a
 * table read is ~2x faster and BYTE-IDENTICAL (same products), so the model
 * output is unchanged. 65536 entries x int16 = 128KB, built once at init.
 * Index = ((uint8)a << 8) | (uint8)b, value = (int8)a * (int8)b. */
static int16_t *gMulLUT = 0L;
static int build_mul_lut(void) {
    int a, b;
    gMulLUT = (int16_t *)malloc(65536L * sizeof(int16_t));
    if (!gMulLUT) return -1;
    for (a = -128; a < 128; a++)
        for (b = -128; b < 128; b++)
            gMulLUT[(((long)(a & 0xFF)) << 8) | (b & 0xFF)] = (int16_t)(a * b);
    return 0;
}

static int big_endian(void) { unsigned short x = 1; return *((unsigned char *)&x) == 0; }
static uint32_t rd32(const unsigned char *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8)
         | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static float rdf(const unsigned char *p) {
    uint32_t u = rd32(p); float f; memcpy(&f, &u, 4); return f;
}
static void swap4(void *v) {
    unsigned char *b = (unsigned char *)v, t;
    t = b[0]; b[0] = b[3]; b[3] = t; t = b[1]; b[1] = b[2]; b[2] = t;
}
static void swapf(float *a, long n) { long i; if (!big_endian()) return; for (i = 0; i < n; i++) swap4(&a[i]); }
static void swap_scales(QuantizedTensor *qt, int n, int size_each) {
    int i; if (!big_endian()) return;
    for (i = 0; i < n; i++) swapf(qt[i].s, size_each / GS);
}

/* Precompute the RoPE rotation table once at init. The expressions are
 * copied verbatim from runq.c's per-token loop, so the table entries are
 * bit-identical to what the reference computes on the fly. Costs
 * seq_len * head_size/2 * 2 floats of RAM (256*8*2*4 = 16K at head 16). */
static int build_rope(Config *p) {
    int hs = p->dim / p->n_heads, half = hs >> 1, k;
    long pos, n = (long)p->seq_len * half;
    float *freq;
    gRopeCos = (float *)malloc(n * sizeof(float));
    gRopeSin = (float *)malloc(n * sizeof(float));
    freq = (float *)malloc((half > 0 ? half : 1) * sizeof(float));
    if (!gRopeCos || !gRopeSin || !freq) return -1;
    /* freq depends only on the head dim (hd = 2k), NOT on pos: compute the
     * expensive powf once per k (4 calls here) instead of seq_len*half. The
     * values are bit-identical to the per-token reference (hd = 2k). */
    for (k = 0; k < half; k++)
        freq[k] = 1.0f / powf(10000.0f, (2 * k) / (float)hs);
    for (pos = 0; pos < p->seq_len; pos++) {
        for (k = 0; k < half; k++) {
            float val = pos * freq[k];
            gRopeCos[pos * half + k] = cosf(val);
            gRopeSin[pos * half + k] = sinf(val);
        }
    }
    free(freq);
    return 0;
}

/* Map weights straight out of the in-RAM checkpoint buffer. Same as runq.c's
 * memory_map_weights but WITHOUT building a full dequantized token table --
 * forward() dequantizes the one needed row per step instead (saves vocab*dim
 * floats of RAM). */
static void map_weights(TransformerWeights *w, Config *p, void *ptr, int shared_classifier) {
    int head_size = p->dim / p->n_heads;
    float *fptr = (float *)ptr;
    w->rms_att_weight = fptr; fptr += p->n_layers * p->dim;
    w->rms_ffn_weight = fptr; fptr += p->n_layers * p->dim;
    w->rms_final_weight = fptr; fptr += p->dim;
    ptr = (void *)fptr;
    w->q_tokens = init_quantized_tensors(&ptr, 1, p->vocab_size * p->dim);
    w->token_embedding_table = 0L;              /* dequantized on the fly */
    w->wq = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_heads * head_size));
    w->wk = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_kv_heads * head_size));
    w->wv = init_quantized_tensors(&ptr, p->n_layers, p->dim * (p->n_kv_heads * head_size));
    w->wo = init_quantized_tensors(&ptr, p->n_layers, (p->n_heads * head_size) * p->dim);
    w->w1 = init_quantized_tensors(&ptr, p->n_layers, p->dim * p->hidden_dim);
    w->w2 = init_quantized_tensors(&ptr, p->n_layers, p->hidden_dim * p->dim);
    w->w3 = init_quantized_tensors(&ptr, p->n_layers, p->dim * p->hidden_dim);
    w->wcls = shared_classifier ? w->q_tokens
              : init_quantized_tensors(&ptr, 1, p->dim * p->vocab_size);
}

/* v2 checkpoint header: [magic u32][version i32][Config 7*i32][shared u8][GS i32]
 * padded to 256 bytes, then the weights. All scalars little-endian. */
static int load_model_mem(Transformer *t, const void *data, long len) {
    const unsigned char *b = (const unsigned char *)data;
    Config *p = &t->config;
    int cfg = (int)sizeof(Config);      /* 28 */
    uint8_t shared; int hs, L;
    if (len < 256) return -1;
    if (rd32(b) != 0x616b3432u) return -1;          /* magic "ak42" */
    if ((int)rd32(b + 4) != 2) return -1;           /* version 2 */
    p->dim        = (int)rd32(b + 8);
    p->hidden_dim = (int)rd32(b + 12);
    p->n_layers   = (int)rd32(b + 16);
    p->n_heads    = (int)rd32(b + 20);
    p->n_kv_heads = (int)rd32(b + 24);
    p->vocab_size = (int)rd32(b + 28);
    p->seq_len    = (int)rd32(b + 32);
    shared = b[8 + cfg];                             /* b[36] */
    GS = (int)rd32(b + 8 + cfg + 1);                 /* b[37..40] */
    if (GS <= 0 || (GS & 7)) return -1;              /* unrolled matmul needs GS % 8 == 0 */
    map_weights(&t->weights, p, (void *)(b + 256), shared);

    /* On big-endian (the Mac) the fp32 regions are byte-swapped in place to
     * native order. No-op on little-endian. */
    hs = p->dim / p->n_heads; L = p->n_layers;
    swapf(t->weights.rms_att_weight,   (long)L * p->dim);
    swapf(t->weights.rms_ffn_weight,   (long)L * p->dim);
    swapf(t->weights.rms_final_weight, p->dim);
    swap_scales(t->weights.q_tokens, 1, p->vocab_size * p->dim);
    swap_scales(t->weights.wq, L, p->dim * (p->n_heads * hs));
    swap_scales(t->weights.wk, L, p->dim * (p->n_kv_heads * hs));
    swap_scales(t->weights.wv, L, p->dim * (p->n_kv_heads * hs));
    swap_scales(t->weights.wo, L, (p->n_heads * hs) * p->dim);
    swap_scales(t->weights.w1, L, p->dim * p->hidden_dim);
    swap_scales(t->weights.w2, L, p->hidden_dim * p->dim);
    swap_scales(t->weights.w3, L, p->dim * p->hidden_dim);
    if (t->weights.wcls != t->weights.q_tokens)
        swap_scales(t->weights.wcls, 1, p->dim * p->vocab_size);
    return 0;
}
'''

# build_tokenizer_mem needs the Tokenizer type, so it is emitted AFTER the
# tokenizer structs (see assembly order below).
part_tokload = '''
/* Tokenizer parsed from an in-RAM buffer (was fopen/fread).
 * format: [max_token_length i32] then per token: [score f32][len i32][bytes].
 *
 * The vocab strings go in ONE block, not vocab_size separate mallocs. On the
 * 68000 Mac, ~2048 small NewPtr calls after the big KV-cache alloc thrash the
 * Memory Manager's free list (O(n^2)) -- that was ~60s of the startup. One
 * allocation makes the load near-instant. gTokBlob is freed in free_tokenizer. */
static char *gTokBlob = 0L;
static void build_tokenizer_mem(Tokenizer *t, const void *data, int vocab_size) {
    const unsigned char *b = (const unsigned char *)data;
    long off, total; int i, slen; char *dst;
    t->vocab_size = vocab_size;
    t->vocab = (char **)malloc(vocab_size * sizeof(char *));
    t->vocab_scores = (float *)malloc(vocab_size * sizeof(float));
    t->sorted_vocab = 0L;
    for (i = 0; i < 256; i++) { t->byte_pieces[i*2] = (unsigned char)i; t->byte_pieces[i*2+1] = '\\0'; }
    t->max_token_length = rd32(b);                   /* little-endian */
    /* pass 1: total bytes for all strings (+1 NUL each) */
    off = 4; total = 0;
    for (i = 0; i < vocab_size; i++) {
        off += 4;                                    /* score */
        slen = (int)rd32(b + off); off += 4;
        total += (long)slen + 1;
        off += slen;
    }
    gTokBlob = (char *)malloc(total > 0 ? total : 1);
    /* pass 2: copy each string into the blob; vocab[i] points into it */
    off = 4; dst = gTokBlob;
    for (i = 0; i < vocab_size; i++) {
        t->vocab_scores[i] = rdf(b + off); off += 4;
        slen = (int)rd32(b + off);         off += 4;
        t->vocab[i] = dst;
        memcpy(dst, b + off, slen); dst[slen] = '\\0';
        dst += slen + 1; off += slen;
    }
}
'''

# neural net blocks: rmsnorm/softmax/matmul/forward (verbatim minus OMP), with
# the v2 speed patches applied below.
core = "\n".join(l for l in slc(282, 482).split("\n") if "#pragma omp" not in l)

# --- patch: token embedding row dequantized on the fly (v1 behavior) ---------
old_emb = "memcpy(x, w->token_embedding_table + token*dim, dim * sizeof(float));"
new_emb = ("{ QuantizedTensor *qt = w->q_tokens; int _i;\n"
           "      for (_i = 0; _i < dim; _i++)\n"
           "          x[_i] = ((float)qt->q[token*dim + _i]) * qt->s[(token*dim + _i) / GS]; }")
assert old_emb in core, "token-embedding memcpy line not found -- runq.c changed"
core = core.replace(old_emb, new_emb)

# --- patch: matmul hot loop (muls.w idiom + 8x unroll; bit-identical) --------
old_matmul = '''void matmul(float* xout, QuantizedTensor *x, QuantizedTensor *w, int n, int d) {
    // W (d,n) @ x (n,) -> xout (d,)
    // by far the most amount of time is spent inside this little function
    // inputs to this function are both quantized

    int i;
    for (i = 0; i < d; i++) {

        float val = 0.0f;
        int32_t ival = 0;
        int in = i * n;

        // do the matmul in groups of GS
        int j;
        for (j = 0; j <= n - GS; j += GS) {
            for (int k = 0; k < GS; k++) {
                ival += ((int32_t) x->q[j + k]) * ((int32_t) w->q[in + j + k]);
            }
            val += ((float) ival) * w->s[(in + j) / GS] * x->s[j / GS];
            ival = 0;
        }

        xout[i] = val;
    }
}'''
new_matmul = '''void matmul(float* xout, QuantizedTensor *x, QuantizedTensor *w, int n, int d) {
    /* W (d,n) @ x (n,) -> xout (d,) -- THE hot loop (~90% of a token).
     * int8 x int8 products come from gMulLUT (a 128KB table) instead of the
     * 68000's slow MULS.W. The products are IDENTICAL, so the output is
     * byte-for-byte the same as the reference -- this is a pure speedup, not
     * an approximation. x[k] is pre-shifted into the high index byte once per
     * matmul (x8buf) so the inner MAC is just: table[x8 | w]. Unrolled 8x
     * (GS % 8 == 0, checked at load). No divide in the loop (both scale arrays
     * walked with pointers). Same per-group float summation order. */
    int i, j, k;
    static unsigned short x8buf[512];   /* ((uint8)x[k]) << 8, reused per row */
    const int8_t *wp  = w->q;
    const float  *wsp = w->s;
    for (k = 0; k < n; k++)
        x8buf[k] = (unsigned short)(((unsigned)(unsigned char)x->q[k]) << 8);
    for (i = 0; i < d; i++) {
        float val = 0.0f;
        const float          *xsp = x->s;
        const unsigned short *x8  = x8buf;
        for (j = 0; j <= n - GS; j += GS) {
            int32_t ival = 0;
            for (k = 0; k < GS; k += 8) {
                ival += gMulLUT[x8[0] | (unsigned char)wp[0]];
                ival += gMulLUT[x8[1] | (unsigned char)wp[1]];
                ival += gMulLUT[x8[2] | (unsigned char)wp[2]];
                ival += gMulLUT[x8[3] | (unsigned char)wp[3]];
                ival += gMulLUT[x8[4] | (unsigned char)wp[4]];
                ival += gMulLUT[x8[5] | (unsigned char)wp[5]];
                ival += gMulLUT[x8[6] | (unsigned char)wp[6]];
                ival += gMulLUT[x8[7] | (unsigned char)wp[7]];
                x8 += 8; wp += 8;
            }
            val += ((float) ival) * (*wsp++) * (*xsp++);
        }
        xout[i] = val;
    }
}'''
assert old_matmul in core, "matmul function not found verbatim -- runq.c changed"
core = core.replace(old_matmul, new_matmul)

# --- patch: RoPE from the precomputed table (bit-identical values) ----------
old_rope = '''        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float freq = 1.0f / powf(10000.0f, head_dim / (float)head_size);
            float val = pos * freq;
            float fcr = cosf(val);
            float fci = sinf(val);'''
new_rope = '''        for (int i = 0; i < dim; i+=2) {
            int head_dim = i % head_size;
            float fcr = gRopeCos[pos * (head_size >> 1) + (head_dim >> 1)];
            float fci = gRopeSin[pos * (head_size >> 1) + (head_dim >> 1)];'''
assert old_rope in core, "RoPE block not found -- runq.c changed"
core = core.replace(old_rope, new_rope)

# --- patch: hoist sqrtf(head_size) out of the attention score loop ----------
old_scale = "                score /= sqrtf(head_size);"
new_scale = "                score /= gAttnScale;      /* == sqrtf(head_size), hoisted */"
assert old_scale in core, "attention scale line not found -- runq.c changed"
core = core.replace(old_scale, new_scale)

# --- patch: skip final rmsnorm + classifier during prompt prefill -----------
old_final = '''    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);'''
new_final = '''    // during prompt prefill the logits are never read: skip the final
    // rmsnorm + the dim x vocab classifier matmul (~30% of a forward pass)
    if (!gWantLogits) return s->logits;

    // final rmsnorm
    rmsnorm(x, x, w->rms_final_weight, dim);'''
assert old_final in core, "final rmsnorm block not found -- runq.c changed"
core = core.replace(old_final, new_final)

# tokenizer structs + compare_tokens (verbatim).
tok_structs = slc(486, 502)
# free_tokenizer + decode + safe_printf + str_lookup + encode (verbatim), except
# decode's sscanf("<0x%02hhX>") -- Retro68's sscanf doesn't handle the hh length
# modifier, so byte-fallback tokens rendered literally as "<0x0A>". Parse the two
# hex digits by hand instead.
tok_rest = slc(530, 691)
_old_sscanf = ('''    unsigned char byte_val;
    if (sscanf(piece, "<0x%02hhX>", &byte_val) == 1) {
        piece = (char*)t->byte_pieces + byte_val * 2;
    }''')
_new_sscanf = ('''    unsigned char byte_val;
    if (piece[0]=='<' && piece[1]=='0' && piece[2]=='x' && piece[5]=='>' && piece[6]=='\\0') {
        int _hi = piece[3], _lo = piece[4];
        _hi = (_hi<='9') ? _hi-'0' : ((_hi|0x20)-'a'+10);
        _lo = (_lo<='9') ? _lo-'0' : ((_lo|0x20)-'a'+10);
        if (_hi>=0 && _hi<16 && _lo>=0 && _lo<16) {
            byte_val = (unsigned char)(_hi*16 + _lo);
            piece = (char*)t->byte_pieces + byte_val * 2;
        }
    }''')
assert _old_sscanf in tok_rest, "decode sscanf block not found -- runq.c changed"
tok_rest = tok_rest.replace(_old_sscanf, _new_sscanf)

# The vocab strings now live in one gTokBlob (see build_tokenizer_mem), so
# free the block once instead of freeing each t->vocab[i] (which would be an
# invalid free -- they point INTO the block).
_old_free = "void free_tokenizer(Tokenizer* t) {\n    for (int i = 0; i < t->vocab_size; i++) { free(t->vocab[i]); }"
_new_free = "void free_tokenizer(Tokenizer* t) {\n    free(gTokBlob); gTokBlob = 0L;    /* strings are one block now, not per-token */"
assert _old_free in tok_rest, "free_tokenizer not found verbatim -- runq.c changed"
tok_rest = tok_rest.replace(_old_free, _new_free)

# sampler: structs, sample_*, build_sampler, sample, random_* (verbatim), then
# sample() swapped for the 68000-friendly top-k version.
sampler = "\n".join(l for l in slc(692, 834).split("\n") if "#pragma omp" not in l)

old_sample = '''int sample(Sampler* sampler, float* logits) {
    // sample the token given the logits and some hyperparameters
    int next;
    if (sampler->temperature == 0.0f) {
        // greedy argmax sampling: take the token with the highest probability
        next = sample_argmax(logits, sampler->vocab_size);
    } else {
        // apply the temperature to the logits
        for (int q=0; q<sampler->vocab_size; q++) { logits[q] /= sampler->temperature; }
        // apply softmax to the logits to get the probabilities for next token
        softmax(logits, sampler->vocab_size);
        // flip a (float) coin (this is our source of entropy for sampling)
        float coin = random_f32(&sampler->rng_state);
        // we sample from this distribution to get the next token
        if (sampler->topp <= 0 || sampler->topp >= 1) {
            // simply sample from the predicted probability distribution
            next = sample_mult(logits, sampler->vocab_size, coin);
        } else {
            // top-p (nucleus) sampling, clamping the least likely tokens to zero
            next = sample_topp(logits, sampler->vocab_size, sampler->topp, sampler->probindex, coin);
        }
    }
    return next;
}'''
new_sample = '''#define GPT_TOPK 40

static int sample_topk(Sampler *sampler, float *logits) {
    /* top-k sampling built for the 68000: one early-out pass selects the k
     * highest logits (no softmax over the whole vocab, no qsort -- those cost
     * seconds per token in software float), then a temperature softmax over
     * just those k and one draw. */
    ProbIndex *pi = sampler->probindex;
    int n = sampler->vocab_size, k = GPT_TOPK;
    int i, j, cnt = 0, mini = 0;
    float coin, maxv, sum, r, cdf;
    if (k > n) k = n;
    for (i = 0; i < n; i++) {
        float v = logits[i];
        if (cnt < k) {
            pi[cnt].prob = v; pi[cnt].index = i;
            if (++cnt == k) {
                mini = 0;
                for (j = 1; j < k; j++) if (pi[j].prob < pi[mini].prob) mini = j;
            }
        } else if (v > pi[mini].prob) {
            pi[mini].prob = v; pi[mini].index = i;
            mini = 0;
            for (j = 1; j < k; j++) if (pi[j].prob < pi[mini].prob) mini = j;
        }
    }
    maxv = pi[0].prob;
    for (i = 1; i < cnt; i++) if (pi[i].prob > maxv) maxv = pi[i].prob;
    sum = 0.0f;
    for (i = 0; i < cnt; i++) {
        pi[i].prob = expf((pi[i].prob - maxv) / sampler->temperature);
        sum += pi[i].prob;
    }
    coin = random_f32(&sampler->rng_state);
    r = coin * sum;
    cdf = 0.0f;
    for (i = 0; i < cnt; i++) {
        cdf += pi[i].prob;
        if (r < cdf) return pi[i].index;
    }
    return pi[cnt - 1].index;
}

int sample(Sampler* sampler, float* logits) {
    if (sampler->temperature == 0.0f)
        return sample_argmax(logits, sampler->vocab_size);   /* greedy: exact */
    return sample_topk(sampler, logits);
}'''
assert old_sample in sampler, "sample() not found verbatim -- runq.c changed"
sampler = sampler.replace(old_sample, new_sample)

api = '''
/* ---------------------------------------------------------------------------
 * Public engine API (replaces runq.c's generate/chat/main)
 * ------------------------------------------------------------------------- */
static Transformer gT;
static Tokenizer   gTok;
static Sampler     gSmp;
static int         gReady = 0;

int GptInitMem(const void *modelData, long modelLen,
               const void *tokData, long tokLen,
               float temperature, float topp, unsigned long seed) {
    (void)tokLen;
    if (gReady) GptShutdown();
    PROG(1);
    if (load_model_mem(&gT, modelData, modelLen) != 0) return -1;
    if (build_mul_lut() != 0) return -1;      /* int8xint8 product table */
    PROG(2);
    if (build_rope(&gT.config) != 0) return -1;
    gAttnScale = sqrtf(gT.config.dim / gT.config.n_heads);
    PROG(4);
    malloc_run_state(&gT.state, &gT.config);
    PROG(5);
    build_tokenizer_mem(&gTok, tokData, gT.config.vocab_size);
    PROG(6);
    build_sampler(&gSmp, gT.config.vocab_size, temperature, topp,
                  (unsigned long long)seed);
    PROG(7);
    gReady = 1;
    return 0;
}

int  GptReady(void)  { return gReady; }
int  GptSeqLen(void) { return gReady ? gT.config.seq_len : 0; }

/* DEBUG: raw IEEE bits of a few loaded weights (to compare host vs big-endian
 * Mac) and the argmax token predicted from BOS. */
unsigned long GptDbgBits(int i) {
    float f = 0.0f; uint32_t u;
    if (!gReady) return 0;
    if      (i == 0) f = gT.weights.rms_att_weight[0];
    else if (i == 1) f = gT.weights.q_tokens[0].s[0];
    else if (i == 2) f = gT.weights.wq[0].s[0];
    else if (i == 3) f = gT.weights.w1[0].s[0];
    memcpy(&u, &f, 4);
    return (unsigned long)u;
}
int GptDbgFirstTok(void) {
    float *logits;
    if (!gReady) return -1;
    gWantLogits = 1;
    logits = forward(&gT, 1, 0);      /* BOS at position 0 */
    return sample_argmax(logits, gT.config.vocab_size);
}

/* DEBUG: encode `prompt`, run the prompt through, return promptLen, first two
 * token ids, and the greedy first generated token. For host-vs-Mac diffing. */
void GptDbgProbe(const char *prompt, int *pLen, int *pT0, int *pT1, int *pFirst) {
    int ptoks[64], n = 0, pos, token;
    *pLen = *pT0 = *pT1 = *pFirst = -1;
    if (!gReady) return;
    encode(&gTok, (char *)prompt, 1, 0, ptoks, &n);
    *pLen = n;
    if (n > 0) *pT0 = ptoks[0];
    if (n > 1) *pT1 = ptoks[1];
    token = ptoks[0];
    for (pos = 0; pos < n; pos++) {
        float *logits;
        gWantLogits = (pos == n - 1);
        logits = forward(&gT, token, pos);
        if (pos < n - 1) token = ptoks[pos + 1];
        else *pFirst = sample_argmax(logits, gT.config.vocab_size);
    }
    gWantLogits = 1;
}

void GptShutdown(void) {
    if (!gReady) return;
    free_sampler(&gSmp);
    free_tokenizer(&gTok);
    /* free the QuantizedTensor arrays (the .q/.s point into the resource, which
     * the Resource Manager owns -- don't free those). */
    free(gT.weights.q_tokens);
    free(gT.weights.wq); free(gT.weights.wk); free(gT.weights.wv); free(gT.weights.wo);
    free(gT.weights.w1); free(gT.weights.w2); free(gT.weights.w3);
    if (gT.weights.wcls != gT.weights.q_tokens) free(gT.weights.wcls);
    free_run_state(&gT.state);
    if (gRopeCos) { free(gRopeCos); gRopeCos = 0L; }
    if (gRopeSin) { free(gRopeSin); gRopeSin = 0L; }
    if (gMulLUT)  { free(gMulLUT);  gMulLUT  = 0L; }
    gWantLogits = 1;
    gReady = 0;
}

/* Generate a continuation of `prompt`, streaming decoded pieces to emit().
 * tick (may be NULL) is called after every forward pass:
 *   phase 0 = reading the prompt   (done/total = prompt positions)
 *   phase 1 = generating the reply (done/total = new tokens)
 * Return 0 from tick to stop cleanly (user cancel / app decides it has
 * enough). The app uses tick to pump its event loop, so the Mac stays
 * responsive across a multi-minute reply. */
void GptGenerate(const char *prompt, int maxNewTokens,
                 GptEmit emit, GptTick tick, void *ctx) {
    int seqcap, plen, promptLen, token, pos, total, next, generated;
    int *ptoks;
    const char *p;
    if (!gReady || emit == 0L) return;
    if (prompt == 0L) prompt = "";
    seqcap = gT.config.seq_len;

    plen = 0; p = prompt; while (p[plen]) plen++;
    ptoks = (int *)malloc((size_t)(plen + 3) * sizeof(int));
    if (!ptoks) return;
    promptLen = 0;
    encode(&gTok, (char *)prompt, 1, 0, ptoks, &promptLen);
    if (promptLen < 1) { free(ptoks); return; }
    if (promptLen > seqcap - 8) promptLen = seqcap - 8;  /* leave room to reply */

    token = ptoks[0];
    pos = 0;
    generated = 0;
    total = promptLen + maxNewTokens;
    if (total > seqcap) total = seqcap;

    while (pos < total) {
        int prefill = (pos < promptLen - 1);
        float *logits;
        gWantLogits = !prefill;
        logits = forward(&gT, token, pos);
        if (prefill) next = ptoks[pos + 1];
        else         next = sample(&gSmp, logits);
        pos++;
        if (next == 1) break;                    /* BOS: the post ended */
        if (pos >= promptLen) {
            char *piece = decode(&gTok, token, next);
            if (piece && piece[0] != '\\0') emit(piece, ctx);
            generated++;
        }
        if (tick) {
            int go = prefill ? tick(0, pos, promptLen, ctx)
                             : tick(1, generated, maxNewTokens, ctx);
            if (!go) break;
        }
        token = next;
    }
    gWantLogits = 1;
    free(ptoks);
}
'''

out = "\n".join([header, part_structs, part_quant, part_loader, core,
                 tok_structs, part_tokload, tok_rest, sampler, api])
open(OUT, "w").write(out)
print("wrote", OUT, "(", len(out.split(chr(10))), "lines )")
