#!/usr/bin/env node
// Slurp the Open Source AI one-pager out of Pages into apps/osai/content/core.md,
// and copy the Public Benefit AI map from docsrepo into apps/osai/content/map.md.
//
//   pnpm osai:slurp                      # reads ../docsrepo/opensourceai/1pager.pages
//   node scripts/osai/slurp.mjs <file.pages>
//
// The Pages document is the canonical text; this script never writes to it.
// It asks Pages (AppleScript) to export the document as RTF, converts that to
// HTML with textutil, and turns the HTML into the small markdown dialect that
// src/lib/osai/core.ts renders: "# title", one lede paragraph, "## section"
// headings, paragraphs, "- bullets", "**Label:** note" lines, and "**Pros**" /
// "**Cons**" lists. Pros/cons tables and two-column bullet tables in Pages
// become those lists. SF Symbols glyphs (private-use code points) have no web
// equivalent: the battery after "Traction:" becomes the word "low", the rest
// are dropped.

import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.resolve(here, '..', '..')
const docsrepo = path.resolve(repo, '..', 'docsrepo', 'opensourceai')
const pagesFile = path.resolve(process.argv[2] ?? path.join(docsrepo, '1pager.pages'))
const mapFile = path.join(docsrepo, 'public-benefit-ai-map.md')
const outDir = path.join(repo, 'apps', 'osai', 'content')

if (!existsSync(pagesFile)) {
  console.error(`not found: ${pagesFile}`)
  process.exit(1)
}

// 1. Pages → RTF (export only; the document is closed without saving).
const tmp = mkdtempSync(path.join(tmpdir(), 'osai-slurp-'))
const rtf = path.join(tmp, 'core.rtf')
const script = `
set src to POSIX file "${pagesFile}"
set dst to POSIX file "${rtf}"
tell application "Pages"
  set d to open src
  export d to dst as formatted text
  close d saving no
end tell`
execFileSync('osascript', ['-e', script], { stdio: ['ignore', 'ignore', 'inherit'] })

// 2. RTF → HTML.
const html = execFileSync('textutil', ['-convert', 'html', '-stdout', rtf], { encoding: 'utf8' })

// 3. HTML → markdown.
const md = convert(html)
const stamp = new Date().toISOString().slice(0, 10)
const header = `<!-- generated by scripts/osai/slurp.mjs from ${path.basename(pagesFile)} on ${stamp}. Edit the Pages document, not this file. -->\n\n`
writeFileSync(path.join(outDir, 'core.md'), header + md + '\n')
console.log(`wrote apps/osai/content/core.md (${md.split('\n').length} lines)`)

// 4. The Public Benefit AI map, as is.
if (existsSync(mapFile)) {
  copyFileSync(mapFile, path.join(outDir, 'map.md'))
  console.log('wrote apps/osai/content/map.md')
} else {
  console.warn(`map not found, left as is: ${mapFile}`)
}

// ---------------------------------------------------------------------------

function convert(html) {
  const body = (html.match(/<body[^>]*>([\s\S]*)<\/body>/i) ?? [, html])[1]
  const blocks = []
  let sawTitle = false
  const re = /<table[\s\S]*?<\/table>|<ul[\s\S]*?<\/ul>|<p[\s\S]*?<\/p>/gi
  for (const m of body.matchAll(re)) {
    const chunk = m[0]
    if (/^<table/i.test(chunk)) {
      blocks.push(...table(chunk))
    } else if (/^<ul/i.test(chunk)) {
      blocks.push(list(chunk))
    } else {
      const p = paragraph(chunk, !sawTitle)
      if (p == null) continue
      if (p.startsWith('# ')) sawTitle = true
      blocks.push(p)
    }
  }
  return blocks.filter(Boolean).join('\n\n')
}

function paragraph(p, titleNext) {
  let inner = p.replace(/^<p[^>]*>/i, '').replace(/<\/p>$/i, '')
  inner = inner.replace(/<\/?span[^>]*>/gi, '').replace(/<br\s*\/?>/gi, '')
  if (!stripTags(inner).trim()) return null
  // A bold-only paragraph is a heading.
  const bold = inner.trim().match(/^<b>([\s\S]*?)<\/b>(?:<b><\/b>)*$/i)
  if (bold && !/<\/b>[\s\S]*\S/.test(inner.trim().replace(/^<b>[\s\S]*?<\/b>/i, ''))) {
    const text = clean(stripTags(bold[1]))
    if (text) return (titleNext ? '# ' : '## ') + text
  }
  // "<b>Label:</b> rest" is a note line.
  const note = inner.trim().match(/^<b>([^<]*?:)<\/b>(?:<b><\/b>)*([\s\S]*)$/i)
  if (note) {
    const label = clean(note[1])
    let rest = clean(inline(note[2]))
    if (!rest) rest = 'low'
    return `**${label}** ${rest}`
  }
  return clean(inline(inner))
}

function list(ul) {
  const items = [...ul.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)].map((m) => clean(inline(m[1]))).filter(Boolean)
  return items.map((t) => `- ${t}`).join('\n')
}

function table(t) {
  const out = []
  for (const m of t.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)) {
    const cell = m[1]
    if (!stripTags(cell).trim()) continue
    const label = cell.match(/<p[^>]*>\s*(?:<span[^>]*>)?\s*<b>(Pros|Cons)<\/b>/i)
    const ul = cell.match(/<ul[\s\S]*?<\/ul>/i)
    if (label) out.push(`**${label[1]}**` + (ul ? '\n' + list(ul[0]) : ''))
    else if (ul) out.push(list(ul[0]))
    else out.push(clean(inline(cell.replace(/<\/?p[^>]*>/gi, ' '))))
  }
  // Two plain bullet columns are one list.
  if (out.length === 2 && out.every((b) => b.startsWith('- '))) return [out.join('\n')]
  return out
}

function inline(h) {
  return h
    .replace(/<\/?span[^>]*>/gi, '')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<b>\s*<\/b>|<i>\s*<\/i>/gi, '')
    .replace(/<b>([\s\S]*?)<\/b>/gi, (_, s) => wrap(s, '**'))
    .replace(/<i>([\s\S]*?)<\/i>/gi, (_, s) => wrap(s, '*'))
    .replace(/<[^>]+>/g, '')
}

// Markers go inside the surrounding whitespace: "<i>OLMo: </i>x" → "*OLMo:* x".
function wrap(s, mark) {
  const lead = s.match(/^\s*/)[0]
  const trail = s.match(/\s*$/)[0]
  const core = s.trim()
  if (!core) return lead + trail
  return `${lead}${mark}${core}${mark}${trail}`
}

function stripTags(h) {
  return h.replace(/<[^>]+>/g, '')
}

function clean(s) {
  return decode(s)
    .replace(/\u{1006E9}/gu, 'low') // SF Symbols battery
    .replace(/[\u{E000}-\u{F8FF}\u{F0000}-\u{FFFFD}\u{100000}-\u{10FFFD}]/gu, '') // other private-use glyphs
    .replace(/\s+/g, ' ')
    .trim()
}

function decode(s) {
  return s
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)))
}
