#!/usr/bin/env node
// Scope the synth web-UI stylesheets (../vibeceo/web/public/<synth>/ui/<synth>/styles.css)
// so all of them can live on one page: every selector is prefixed with
// .skin-<synth>, and `body`/`html` rules become the wrapper itself.
// Output: src/app/jam/alt/skins.css (committed — Vercel can't see vibeceo).
//
//   node scripts/jam/build-skins.mjs
import postcss from 'postcss';
import prefixer from 'postcss-prefix-selector';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const HILMA = resolve(__dirname, '..', '..');
const PUB = resolve(HILMA, '..', 'vibeceo', 'web', 'public');
const SKINS = ['jb01', 'jb202', 'jt10', 'jt30', 'jt90'];

let out = '';
const imports = new Set();   // @import must come first in the combined file
for (const s of SKINS) {
  const src = readFileSync(join(PUB, s, 'ui', s, 'styles.css'), 'utf-8');
  const res = await postcss([
    prefixer({
      prefix: `.skin-${s}`,
      transform(prefix, selector, prefixed) {
        const t = selector.trim();
        if (t === 'body' || t === 'html' || t === 'html, body' || t === '*') return prefix;
        if (t.startsWith('body ')) return prefix + t.slice(4);
        if (t.startsWith(':root')) return prefix + t.slice(5);
        return prefixed;
      },
    }),
  ]).process(src, { from: undefined });
  // The originals size the page (min-height: 100vh, centered flex body); inside
  // a sheet the wrapper is just a card.
  const css = res.css
    .replace(/@import[^\n]*\n/g, (m) => { imports.add(m.trim()); return ''; })
    .replace(/min-height:\s*100vh;?/g, '')
    .replace(/(\.skin-[a-z0-9]+)\s*\{([^}]*)display:\s*flex;([^}]*)\}/, '$1 {$2display:block;$3}');
  out += `\n/* ---------- ${s} ---------- */\n${css}\n`;
}
out = `/* Generated by scripts/jam/build-skins.mjs — do not edit.\n * Scoped copies of the synth web-UI stylesheets from ../vibeceo/web/public. */\n${[...imports].join('\n')}\n` + out;
const dest = join(HILMA, 'src', 'app', 'jam', 'alt', 'skins.css');
writeFileSync(dest, out);
console.log(`→ ${dest} ${(out.length / 1024).toFixed(0)} KB`);
