#!/usr/bin/env node
// Bundle ../vibeceo/jambot for the browser → public/jam/jambot-web.js
//
// Node-only modules (fs, path, os, url, module, child_process,
// node-web-audio-api) are replaced by the shims in ./shims. Every JSON/WAV
// jambot reads at runtime is embedded through the `virtual:jam-files`
// module (see shims/fs.js).
//
//   pnpm jam:build
//
// The output is committed: Vercel builds hilma alone and can't see
// ../vibeceo, so the bundle has to travel with this repo.

import * as esbuild from 'esbuild';
import { readFileSync, readdirSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const HILMA = resolve(__dirname, '..', '..');
const VIBECEO = resolve(HILMA, '..', 'vibeceo');
const JAMBOT = join(VIBECEO, 'jambot');
const OUT = join(HILMA, 'public', 'jam', 'jambot-web.js');

// --- virtual file system -----------------------------------------------------

const files = {};   // 'jambot/params/jb01-params.json' -> { text } | { base64 }
const dirs = {};    // 'jambot/presets/jb01/kits' -> ['default.json', ...]

function addFile(abs) {
  const key = relative(VIBECEO, abs).split('\\').join('/');
  const buf = readFileSync(abs);
  files[key] = abs.endsWith('.wav') ? { base64: buf.toString('base64') } : { text: buf.toString('utf-8') };
}

function addDir(abs, filter = () => true) {
  const key = relative(VIBECEO, abs).split('\\').join('/');
  const names = [];
  for (const name of readdirSync(abs)) {
    const p = join(abs, name);
    const st = statSync(p);
    if (st.isDirectory()) { names.push(name); addDir(p, filter); }
    else if (filter(name)) { names.push(name); addFile(p); }
  }
  dirs[key] = names;
}

addFile(join(JAMBOT, 'library.json'));
addDir(join(JAMBOT, 'params'), n => n.endsWith('.json'));
addDir(join(JAMBOT, 'presets'), n => n.endsWith('.json'));
for (const synth of ['jb200', 'jb202', 'jt10', 'jt30', 'jt90']) {
  addFile(join(VIBECEO, 'web', 'public', synth, 'dist', 'presets.json'));
}
addDir(join(VIBECEO, 'web', 'public', 'jt90', 'samples'), n => n.endsWith('.wav'));

// Tool modules that only make sense with a file system / sox. tools/index.js
// references them as dynamic-import thunks (DEFAULT_TOOL_MODULES), which
// would otherwise drag them — and node builtins like zlib — into the bundle.
const EXCLUDED_TOOL_MODULES = /(^|\/)(analyze-tools|jbs-tools|sampler-tools|render-tools|jb200-tools)\.js$/;

const virtualFiles = {
  name: 'jam-virtual-files',
  setup(build) {
    build.onResolve({ filter: /^virtual:jam-files$/ }, () => ({ path: 'virtual:jam-files', namespace: 'jam' }));
    build.onLoad({ filter: /.*/, namespace: 'jam' }, () => ({
      contents: `export const FILES = ${JSON.stringify({ files, dirs })};`,
      loader: 'js',
    }));
    build.onResolve({ filter: EXCLUDED_TOOL_MODULES }, args => ({ path: args.path, namespace: 'jam-empty' }));
    build.onLoad({ filter: /.*/, namespace: 'jam-empty' }, () => ({ contents: 'export {};', loader: 'js' }));
  },
};

// --- build -------------------------------------------------------------------

const shim = name => join(__dirname, 'shims', `${name}.js`);
const jambotRev = (() => {
  try { return execSync('git rev-parse --short HEAD', { cwd: JAMBOT }).toString().trim(); } catch { return 'unknown'; }
})();
const stamp = `${new Date().toISOString().slice(0, 10)}+jambot@${jambotRev}`;

mkdirSync(dirname(OUT), { recursive: true });

const result = await esbuild.build({
  entryPoints: [join(__dirname, 'jambot-web-entry.js')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2020', 'safari15'],
  outfile: OUT,
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  logLevel: 'info',
  metafile: true,
  plugins: [virtualFiles],
  alias: {
    fs: shim('fs'), 'node:fs': shim('fs'),
    path: shim('path'), 'node:path': shim('path'),
    os: shim('os'), 'node:os': shim('os'),
    url: shim('url'), 'node:url': shim('url'),
    module: shim('module'), 'node:module': shim('module'),
    child_process: shim('child_process'), 'node:child_process': shim('child_process'),
    'node-web-audio-api': shim('node-web-audio-api'),
  },
  loader: { '.md': 'text', '.json': 'json' },
  define: {
    __JAM_BUILD__: JSON.stringify(stamp),
    'process.env.NODE_ENV': '"production"',
  },
  banner: {
    js: `/* Jambot browser bundle ${stamp} — generated by scripts/jam/build-jambot.mjs, do not edit */\nvar process=globalThis.process||{env:{},cwd:()=>"/",platform:"browser"};`,
  },
});

const bytes = statSync(OUT).size;
console.log(`\n→ ${relative(HILMA, OUT)}  ${(bytes / 1024).toFixed(0)} KB  (${stamp})`);
writeFileSync(join(HILMA, 'public', 'jam', 'jambot-web.meta.json'), JSON.stringify({
  stamp, bytes, inputs: Object.keys(result.metafile.inputs).length,
}, null, 2));
