#!/usr/bin/env -S npx tsx
/*
 * selftest:
 *   1. frame encoding units (word pairing, splitting)
 *   2. live HN fetch (network, no key)
 *   3. live compose for WAKE/NEWS/SAY (needs ANTHROPIC_API_KEY; skip JUKEBOX-style)
 *      — prints the line + phonemes so you can eyeball the voice, and writes
 *      talkingplus/test_utterance.h for the Plus offline build.
 */

import './main-env.ts';
import { writeFileSync } from 'node:fs';
import { encodeUtterance } from './frame.ts';
import { compose } from './compose.ts';
import { topHackerNews } from './feeds.ts';

let failures = 0;
function check(name: string, ok: boolean, detail = ''): void {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
  if (!ok) failures++;
}

// 1. encode a hand-made utterance and sanity-check the frame
{
  const u = {
    mood: 'grumpy' as const,
    moodCode: 1,
    text: 'Good morning. You have three meetings. I have been awake since 1986.',
    words: [
      { display: 'Good', phonemes: 'g UH1 d' },
      { display: 'morning.', phonemes: 'm AO1 r n IH ng' },
      { display: 'three', phonemes: 'TH r IY1' },
      { display: 'meetings.', phonemes: 'm IY1 t IH ng z' },
    ],
  };
  const frame = encodeUtterance(u);
  const lines = frame.split('\r\n');
  check('frame head', /^TKMUTT 4 1$/.test(lines[0]));
  check('frame has T line', lines.some((l) => l.startsWith('T ')));
  check('frame W lines', lines.filter((l) => l.startsWith('W ')).length === 4);
  check('frame ends', lines[lines.length - 2] === 'TKMEND');
}

// 2. HN live
if (process.env.MOOSE_SKIP_NET !== '1') {
  try {
    const s = await topHackerNews(5);
    check('hacker news fetched', s.length >= 3, `${s.length} stories, top: ${s[0]?.title?.slice(0, 50)}`);
  } catch (e) {
    check('hacker news fetched', false, e instanceof Error ? e.message : String(e));
  }
}

// 3. live compose
if (process.env.MOOSE_SKIP_LIVE === '1') {
  console.log('(MOOSE_SKIP_LIVE=1 — skipping live compose)');
} else if (!process.env.ANTHROPIC_API_KEY) {
  console.log('(no ANTHROPIC_API_KEY — skipping live compose)');
} else {
  for (const task of [
    'It is the morning. Greet your human with a short deadpan good-morning line; no briefing data today.',
    `Your human just said: "do you actually remember 1986". Respond in character.`,
  ]) {
    try {
      const u = await compose(task, (s) => console.log(`  ...thinking (${s}s)`));
      check('live compose', u.words.length >= 3, `(${u.mood}) "${u.text}"`);
      console.log('  phonemes: ' + u.words.map((w) => w.phonemes).join(' / '));
      const outPath = process.argv[2];
      if (outPath) {
        const frame = encodeUtterance(u);
        const esc = frame.replace(/\r\n/g, '\\r\\n"\n"');
        writeFileSync(outPath, `/* generated by agent-moose selftest — a real TKM utterance */\nstatic const char gTestUtterance[] =\n"${esc}";\n`);
        console.log(`  (wrote ${outPath})`);
      }
    } catch (e) {
      check('live compose', false, e instanceof Error ? e.message : String(e));
    }
  }
}

console.log(failures === 0 ? '\nALL CHECKS PASSED' : `\n${failures} CHECK(S) FAILED`);
process.exit(failures === 0 ? 0 : 1);
