-- Feynd Supabase schema (run once via Supabase SQL editor).
--
-- All tables are prefixed `feynd_` so they coexist cleanly with the other
-- projects in the shared vibeceo8 Supabase instance.
--
-- Identity: the iOS app generates a UUID on first launch, stores it in the
-- Keychain, and sends it as `device_id` in every request. No auth yet —
-- RLS is DISABLED and the Next.js backend is the single trusted writer.

-- ---------------------------------------------------------------- Chats
create table if not exists feynd_chats (
  id uuid primary key default gen_random_uuid(),
  device_id text not null,
  course_id text not null,
  video_id  text,                                  -- nullable: open-ended chats
  title     text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_feynd_chats_device on feynd_chats(device_id, updated_at desc);
create index if not exists idx_feynd_chats_video  on feynd_chats(video_id);

-- -------------------------------------------------------------- Messages
create table if not exists feynd_messages (
  id         uuid primary key default gen_random_uuid(),
  chat_id    uuid not null references feynd_chats(id) on delete cascade,
  role       text not null check (role in ('user','assistant')),
  text       text not null,
  source     text not null default 'text' check (source in ('voice','text','discord','seed')),
  audio_url  text,                                 -- populated lazily by TTS
  created_at timestamptz not null default now()
);
create index if not exists idx_feynd_messages_chat on feynd_messages(chat_id, created_at);

-- Keep feynd_chats.updated_at in sync with the latest message.
create or replace function feynd_touch_chat_updated_at() returns trigger as $$
begin
  update feynd_chats set updated_at = now() where id = new.chat_id;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_feynd_touch_chat on feynd_messages;
create trigger trg_feynd_touch_chat
after insert on feynd_messages
for each row execute function feynd_touch_chat_updated_at();

-- ------------------------------------------------------------- Quizzes
-- One quiz per course+video (lazy-generated by Opus on first request, then
-- reused forever unless we rotate).
create table if not exists feynd_quizzes (
  id           uuid primary key default gen_random_uuid(),
  course_id    text not null,
  video_id     text not null,
  questions    jsonb not null,                     -- [{id, q, options:[a,b,c,d], correct_idx, explanation, concept_ids:[...]}]
  generated_at timestamptz not null default now(),
  unique (course_id, video_id)
);

-- ----------------------------------------------------------- Attempts
create table if not exists feynd_quiz_attempts (
  id           uuid primary key default gen_random_uuid(),
  device_id    text not null,
  course_id    text not null,
  video_id     text not null,
  quiz_id      uuid references feynd_quizzes(id) on delete set null,
  answers      jsonb not null,                     -- [{question_id, user_idx, correct}]
  score        int  not null,
  total        int  not null,
  attempted_at timestamptz not null default now()
);
create index if not exists idx_feynd_attempts_device on feynd_quiz_attempts(device_id, attempted_at desc);
create index if not exists idx_feynd_attempts_video  on feynd_quiz_attempts(video_id);

-- ------------------------------------------------------------- Storage
-- Create a public bucket `feynd-audio` for cached TTS mp3s. Do this in the
-- Supabase Dashboard → Storage once, or via the sql below on a project
-- where you have storage.objects access.
--
--   insert into storage.buckets (id, name, public)
--   values ('feynd-audio', 'feynd-audio', true)
--   on conflict do nothing;
