#!/usr/bin/env -S npx tsx
/*
 * selftest — proves the jukebox pipeline without the Plus:
 *   1. note-name + score parsing units
 *   2. an embedded Daisy Bell chorus -> score -> frame (and optionally writes
 *      jukebox/test_song.h so the Plus offline build can sing it)
 *   3. with ANTHROPIC_API_KEY: a live composition (skip: JUKEBOX_SKIP_LIVE=1)
 */

import './main-env.ts';
import { writeFileSync } from 'node:fs';
import { nameToMidi, parseComposition, encodeScore } from './score.ts';
import { compose } from './compose.ts';

let failures = 0;
function check(name: string, ok: boolean, detail = ''): void {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
  if (!ok) failures++;
}

// ---- 1. units ----
check('C4 = 60', nameToMidi('C4') === 60);
check('A4 = 69', nameToMidi('A4') === 69);
check('F#3 = 54', nameToMidi('F#3') === 54);
check('Bb4 = 70', nameToMidi('Bb4') === 70);

// ---- 2. Daisy Bell (chorus), hand-arranged; lyric windows computed ----
const seq: [string, number][] = [
  // "Dai-sy, Dai-sy, give me your an-swer, do"
  ['D5', 2], ['B4', 1], ['G4', 2], ['D4', 1],
  ['E4', 1], ['F#4', 1], ['G4', 1], ['E4', 1.5], ['G4', 0.5], ['D4', 2.5], ['R', 0.5],
  // "I'm half cra-zy, all for the love of you"
  ['A4', 2], ['D5', 1], ['B4', 2], ['G4', 1],
  ['E4', 1], ['F#4', 1], ['G4', 1], ['A4', 1.5], ['B4', 0.5], ['A4', 2.5], ['R', 0.5],
  // "It won't be a sty-lish mar-riage"
  ['B4', 1], ['C5', 1], ['B4', 1], ['A4', 1], ['D5', 1], ['B4', 1], ['A4', 2], ['R', 1],
  // "I can't af-ford a car-riage"
  ['G4', 1], ['A4', 1], ['B4', 1], ['G4', 1], ['B4', 1], ['A4', 2], ['R', 1],
  // "But you'll look sweet up-on the seat"
  ['D4', 1], ['G4', 1], ['B4', 1], ['A4', 1], ['D4', 1], ['G4', 1], ['B4', 1], ['A4', 1],
  // "of a bi-cy-cle built for two!"
  ['B4', 1], ['C5', 1], ['B4', 1], ['A4', 1], ['G4', 1], ['B4', 1], ['A4', 1.5], ['G4', 2.5],
];
const lyricSpans: [number, number, string][] = [
  [0, 10, 'Dai-sy, Dai-sy, give me your answer, do'],
  [11, 21, "I'm half cra-zy, all for the love of you"],
  [22, 29, "It won't be a sty-lish mar-riage"],
  [30, 36, "I can't af-ford a car-riage"],
  [37, 44, "But you'll look sweet upon the seat"],
  [45, 52, 'of a bi-cy-cle built for two!'],
];
{
  let beat = 0;
  const starts: number[] = [];
  const lines: string[] = ['TITLE: Daisy Bell (Test Song)', 'BPM: 120'];
  for (const [p, b] of seq) {
    starts.push(beat);
    lines.push(`N ${p} ${b}`);
    beat += b;
  }
  starts.push(beat);
  for (const [a, b, text] of lyricSpans) {
    const endIdx = Math.min(b + 1, starts.length - 1);
    lines.push(`L ${starts[a]} ${starts[endIdx]} ${text}`);
  }
  const score = parseComposition(lines.join('\n'));
  check('daisy parses', score.notes.length > 40 && score.lyrics.length === 6,
        `${score.notes.length} notes`);
  check('daisy tpb', score.ticksPerBeat === 30);
  check('daisy lyrics sorted + bounded',
        score.lyrics.every((l, i) => l.endTick <= score.totalTicks &&
          (i === 0 || l.startTick >= score.lyrics[i - 1].startTick)));

  const frame = encodeScore(score);
  const flines = frame.split('\r\n');
  const head = flines[0].match(/^JBXSON (\d+) (\d+) (\d+) (\d+)$/);
  check('frame header', !!head && parseInt(head![1], 10) === score.notes.length &&
        parseInt(head![2], 10) === score.lyrics.length);
  check('frame ends', flines[flines.length - 2] === 'JBXEND');

  const outPath = process.argv[2];
  if (outPath) {
    const esc = frame.replace(/\r\n/g, '\\r\\n"\n"');
    writeFileSync(
      outPath,
      `/* generated by agent-jukebox selftest — Daisy Bell as a JBX frame */\nstatic const char gTestSong[] =\n"${esc}";\n`
    );
    console.log(`(wrote embedded test song -> ${outPath})`);
  }
}

// ---- 3. live composition ----
if (process.env.JUKEBOX_SKIP_LIVE === '1') {
  console.log('(JUKEBOX_SKIP_LIVE=1 — skipping live composition)');
} else if (!process.env.ANTHROPIC_API_KEY) {
  console.log('(no ANTHROPIC_API_KEY — skipping live composition)');
} else {
  const vibe = process.argv[3] ?? 'a triumphant little anthem about a 1986 computer that learned to sing';
  console.log(`\n--- live compose: "${vibe}" ---`);
  try {
    const s = await compose(vibe, (sec) => console.log(`  ...composing (${sec}s)`));
    check('live compose', s.notes.length >= 8 && s.lyrics.length >= 2,
          `"${s.title}" ${s.bpm}bpm ${s.notes.length} notes ${s.lyrics.length} lyric lines ${Math.round(s.totalTicks / 60)}s`);
    for (const l of s.lyrics.slice(0, 4)) console.log(`  | ${l.text}`);
  } catch (e) {
    check('live compose', false, e instanceof Error ? e.message : String(e));
  }
}

console.log(failures === 0 ? '\nALL CHECKS PASSED' : `\n${failures} CHECK(S) FAILED`);
process.exit(failures === 0 ? 0 : 1);
