#!/usr/bin/env node
/*
 * Repo as working directory: run Claude Code inside the repo, persona appended.
 *
 * Why: stock golembot spawns the CLI in the assistant directory (~/golembot/
 * strays), so the only CLAUDE.md Claude Code loads is the generated persona.
 * The repo's own CLAUDE.md — spec-first and verify-behaviour gates, "finish
 * the work", every app's notes — was one sentence away ("read ~/hilma-bot/
 * CLAUDE.md before making repo changes") and mostly not read. A CLAUDE.md
 * `@import` cannot reach it either: the CLI refuses imports (and symlinks)
 * that resolve outside the project directory (tested 2026-09-13; `--add-dir`
 * does not load CLAUDE.md files either). Running with cwd = the repo is the
 * only way to get exactly what an interactive session in the repo gets:
 * CLAUDE.md, .claude/commands, .claude/skills, project settings.
 *
 * Config (golem.yaml, top level): workdir: /absolute/path/to/repo
 * When set, the CLI is spawned with that cwd and the assistant directory's
 * CLAUDE.md (→ AGENTS.md, the persona + system instructions) is passed with
 * `--append-system-prompt`, so it still applies — after the repo's rules.
 * Everything else (skills injection, .golem state, media paths, memory) keeps
 * using the assistant directory; the persona tells the agent that paths in
 * [System: …] lines are relative to it. Session transcripts move to
 * ~/.claude/projects/<workdir>/ — patches/fresh-session.mjs reads them there.
 *
 * Patches dist/workspace.js (key), dist/index.js (hand it over) and
 * dist/engines/claude-code.js (cwd + the appended prompt).
 * Idempotent. Re-run after every `npm i -g golembot` (setup-mini.sh does it).
 */
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const DIST = process.argv[2] || '/opt/homebrew/lib/node_modules/golembot/dist';
const MARKER = 'golembot-repo-workdir-patch';

function patchFile(name, fn) {
  const file = join(DIST, name);
  if (!existsSync(file)) { console.error(`not found: ${file}`); process.exit(1); }
  let src = readFileSync(file, 'utf8');
  if (src.includes(MARKER)) { console.log(`${name}: already patched`); return; }
  const replaceOnce = (anchor, replacement, what) => {
    const i = src.indexOf(anchor);
    if (i < 0) { console.error(`${name} ${what}: anchor not found`); process.exit(2); }
    if (src.indexOf(anchor, i + 1) >= 0) { console.error(`${name} ${what}: anchor not unique`); process.exit(2); }
    src = src.slice(0, i) + replacement + src.slice(i + anchor.length);
  };
  fn(replaceOnce);
  if (!existsSync(file + '.orig')) copyFileSync(file, file + '.orig');
  writeFileSync(file, src);
  console.log('patched ' + file);
}

// ── workspace.js: read the key ──────────────────────────────────────────────
patchFile('workspace.js', (replaceOnce) => {
  replaceOnce(
    `    if (typeof doc.systemPrompt === 'string')
        config.systemPrompt = doc.systemPrompt;`,
    `    if (typeof doc.systemPrompt === 'string')
        config.systemPrompt = doc.systemPrompt;
    // ${MARKER}
    if (typeof doc.workdir === 'string')
        config.workdir = doc.workdir;`,
    'config key',
  );
});

// ── index.js: hand it to the engine ─────────────────────────────────────────
patchFile('index.js', (replaceOnce) => {
  replaceOnce(
    `                mcpConfig: config.mcp,
`,
    `                mcpConfig: config.mcp,
                cwd: config.workdir, // ${MARKER}
`,
    'invoke opts',
  );
});

// ── engines/claude-code.js: cwd + appended persona ──────────────────────────
patchFile('engines/claude-code.js', (replaceOnce) => {
  replaceOnce(
    `        const env = {
            ...process.env,`,
    `        // ${MARKER}: running inside the repo, so the assistant directory's AGENTS.md
        // (persona + system instructions, regenerated by ensureReady before every
        // turn; CLAUDE.md there is only a symlink to it) is not on the CLI's path — append it.
        if (opts.cwd && opts.cwd !== opts.workspace) {
            if (!existsSync(opts.cwd))
                throw new Error(\`workdir does not exist: \${opts.cwd}\`);
            const personaFile = join(opts.workspace, 'AGENTS.md');
            if (existsSync(personaFile)) {
                const persona = readFileSync(personaFile, 'utf8').trim();
                if (persona)
                    args.push('--append-system-prompt', persona);
            }
        }
        const env = {
            ...process.env,`,
    'appended persona',
  );
  replaceOnce(
    `            cwd: opts.workspace,
            env,`,
    `            cwd: opts.cwd || opts.workspace, // ${MARKER}
            env,`,
    'cwd',
  );
  // The file imports from node:fs/promises; add the two sync calls we use.
  replaceOnce(
    `import { homedir } from 'node:os';`,
    `import { homedir } from 'node:os';
import { existsSync, readFileSync } from 'node:fs'; // ${MARKER}`,
    'imports',
  );
});
