// Module: Belgian Secession, 1830–31. Drafted by claude-opus-5 on 2026-09-15
// with scripts/socratic/new-module.ts from: no source material (model knowledge).
// The method and tone are the shared Zeiler sections, copied from negligent-entrustment.
//
// Reviewer notes from the draft:
//   **Everything in this module is written from memory; no source material was supplied. A subject-matter reviewer should check all of it, and particularly the following specifics, any of which I may have misremembered:**
//   
//   *Dates and numbers:* the 3.4m (south) vs 2m (north) population figures for 1815; the 55/55 split in the Second Chamber; the mechanics of the 1815 Fundamental Law vote and whether William counted both abstentions *and* religious-objection votes as assent ("Dutch arithmetic"); the Collegium Philosophicum at Leuven dated to 1825; language decrees issued 1819 and implemented 1823, relaxed 1829–30; the Brussels riot of 25 August 1830 after *La Muette de Portici*; the Four Days of Brussels 23–26 September 1830; independence declared 4 October 1830; National Congress elected 3 November, convened 10 November 1830; monarchy over republic by roughly 174–13; exclusion of the Orange-Nassaus 24 November 1830; constitution of 7 February 1831; Nemours elected February 1831 and declined; Surlet de Chokier as regent; Leopold I sworn 21 July 1831; XVIII Articles June 1831; Ten Days' Campaign 2–12 August 1831; XXIV Articles 15 October 1831; Treaty of London 19 April 1839. I have given the 1831 franchise as "on the order of one percent of the population" rather than a hard number, because I do not trust my recollection of the exact figure.
//   
//   *Constitutional articles:* I have deliberately paraphrased the 1831 constitution's provisions rather than cite article numbers, because my recollection of the numbering (popular sovereignty, freedom of education, freedom of language, state salaries for clergy) is not reliable enough to put in a student's mouth. A reviewer who wants article numbers in the text should add them from the 1831 original, not from the current renumbered constitution.
//   
//   *Interpretive claims I supplied and that are arguable, not settled:* the characterisation of unionism as an "overlapping-consensus bargain" rather than a principled convergence; the claim that William I's policies industrialised Wallonia (Société Générale 1822, Cockerill at Seraing) and that the economic grievance was fiscal and tariff-based rather than about immiseration; the framing of 1830 nationhood as "performed, not inventoried"; and the three-part structure (indictment / claimant / guarantee) in Question 9, which is **my own analytical scaffold**, constructed to give this module the equivalent of the exemplar's two-part prima facie case. It is not a formulation any historian of 1830 would recognise as standard, and a reviewer should decide whether to keep it, rename it, or replace it with a scheme from the literature.
//   
//   *The hypothetical:* the scenario of a Flemish delegate reciting the 1830 case back at the Belgian state is a teaching device I invented; it is not a documented event, and it should not be presented to the student as one. The supporting Flemish Movement chronology I allude to in Question 6 — the nineteenth-century language laws, the Equality Law of 1898, the Dutchification of Ghent University around 1930, the fixing of the language frontier in the early 1960s, and the successive state reforms from 1970 to 2011 — is all from memory and needs verification, including the count of state reforms. The Council of Flanders episode of 1917 and the modern N-VA "confederalism" debate are deliberately left out of the student-facing text because I am least confident about them; a reviewer may want to add the 1917 episode, which is a strong and genuinely awkward variant.
//   
//   *Trigger caution:* I have flagged in the doctrine section that the opera riot is a trigger, not a cause, but historians vary in how much weight they give the theatrical episode at all, and the tutor should not let a student make it the explanation.

import { negligentEntrustment as zeiler } from './negligent-entrustment'
import type { Module } from '../types'

export const belgianRevolution: Module = {
  id: "belgian-revolution",
  title: "Belgian Secession, 1830–31",
  subtitle: "The 1831 constitution and the \"does it justify secession from Belgium?\" hypothetical",
  course: "History · Revolutions",
  source: "Modelled on Professor Kathryn Zeiler's Socratic method, Boston University School of Law, applied to the Belgian Revolution",
  framing: `You are about to run a one-on-one Socratic tutoring session on the Belgian Revolution of 1830 and the constitution of 1831. The subject is history, but the *method* is a law school method — it comes from a real transcript of Professor Kathryn Zeiler teaching at BU Law, and the moves below are hers: make the student commit to a position before they argue, refuse to let a recitation of facts pass as an argument, force them to build the other side, press them on where their principle stops, and only then name the skill they just used. History students are, if anything, more prone than law students to the central error — answering a "why" question with a chronology. Your job is not to transmit the story of 1830. It is to make the student build a justification, test it, and discover what it licenses that they did not intend.`,
  hypotheticalTitle: "the \"secession from Belgium\" extension",

  doctrine: `**The settlement being revolted against.** The Congress of Vienna (1815) welded the former Austrian Netherlands and the Prince-Bishopric of Liège onto the Dutch Republic's successor state to make the United Kingdom of the Netherlands under William I — a "barrier" state against France. This was a construction of great-power strategy, not of consent. The south had roughly 3.4 million people to the north's 2 million, and the Belgian provinces had been separate from the north since the 1580s.

**The catalogue of grievances.** The tutor must be able to sort these, not just list them — the sorting is the teaching point.

- **Constitutional/representational.** The Fundamental Law of 1815 was submitted to southern notables and rejected by a majority of those voting; William counted abstentions as assent and counted those who objected on religious-liberty grounds as assenting (since the Vienna powers had mandated religious freedom anyway), and declared it adopted. Southerners called this *la arithmétique hollandaise* — "Dutch arithmetic." The Second Chamber then seated 55 members from each half despite the population disparity, which meant the south could never win a vote by being right *and* numerous.
- **Religious.** A Calvinist king over an overwhelmingly Catholic population; state control of clerical training, above all the *Collegium Philosophicum* at Leuven (1825), which required future priests to pass through a state-run philosophical college; running conflict with Rome over the Concordat; earlier prosecution and exile of the Bishop of Ghent, de Broglie.
- **Linguistic.** Decrees of 1819, implemented from 1823, made Dutch the sole official language in the Flemish and Brabant provinces and Limburg — resented above all by the French-speaking *elite of Flanders itself*. Relaxed in 1829–30, too late.
- **Fiscal and economic.** The merger of the south's small debt with the north's enormous one; Dutch-style excises on grinding grain (*mouture*) and slaughtering (*abattage*), regressive and hated; a commercial policy tilted toward northern free-trading merchants against southern industrialists who wanted protection.
- **Administrative.** Ministers, senior officials, army officers and diplomats drawn overwhelmingly from the north.
- **Civil liberties.** Press prosecutions, most famously that of the Brussels journalist Louis de Potter, tried and exiled in 1830.

**The liberal-Catholic union (*unionisme*), 1827–29.** The decisive political fact. Liberals — anticlerical, constitutionalist, French-educated — and Catholics — clerical, traditionalist, hostile to the Enlightenment state — had been enemies. From 1827–28 they combined against William. The bridge was a *negative* one: both wanted the state's hand off. Catholics wanted freedom of education because the state's education was in Protestant hands; liberals wanted freedom of press and association because the state was censoring them. Liberal Catholicism of the Lamennais school gave the Catholic side a vocabulary for demanding liberty rather than privilege. The union produced a mass petition campaign in 1828–29, which the king rejected. **Students go wrong here** by treating unionism as a discovery of shared principle. It was an overlapping-consensus bargain against a common adversary — and it began coming apart within fifteen years, into the school wars of the mid-century.

**The sequence of 1830.** Riot in Brussels on 25 August 1830, after a performance of Auber's *La Muette de Portici* at the Théâtre de la Monnaie, in the wash of the July Revolution in Paris. **The initial demand was not independence** — it was *séparation administrative*: two administrations under one Orange crown. William answered with troops. His son Prince Frederick's forces were beaten back in the Four Days of Brussels, 23–26 September, fought largely in the Parc. Only then, on 4 October 1830, did the Provisional Government proclaim independence.

**The National Congress — the constituent act.** Elected 3 November 1830 on a narrow tax-based franchise; convened 10 November. It voted independence, voted a constitutional monarchy over a republic (by a lopsided margin, roughly 174 to 13), and voted the perpetual exclusion of the House of Orange-Nassau on 24 November. It promulgated the **constitution of 7 February 1831**.

**The 1831 constitution — the anchor text.** Drafted quickly, borrowing from the French constitution of 1791 and Charter of 1830, the Dutch Fundamental Law, and English practice; it was for decades the most copied constitution in Europe.
- Popular sovereignty stated flatly: *all powers emanate from the Nation*.
- A hereditary constitutional monarch with **only** the powers the constitution grants him; the king is inviolable, his ministers responsible, and every royal act requires a ministerial countersignature.
- The union's price, written down as enumerated freedoms: **freedom of worship** and of its public exercise, with the state barred from interfering in the appointment of ministers of religion (Catholic demand) but also civil marriage required to precede religious (liberal demand); **freedom of education** (the central Catholic demand); **freedom of the press**, with no censorship and press offences tried by jury; **freedom of association**, an innovation; **freedom of language** — language use is *free*, regulable only for official acts and the courts.
- Strong communal and provincial autonomy.
- **Not democratic.** A property/tax franchise, on the order of one percent of the population.

**The external bargain — and the anchor result.** Independence was not self-executing. The London Conference of the powers opened in November 1830. The Congress first elected the duc de Nemours, son of Louis-Philippe, in February 1831; Britain blocked it and Louis-Philippe declined. A regency under Surlet de Chokier bridged the gap until Leopold of Saxe-Coburg took the oath on 21 July 1831. Belgium accepted the Treaty of the XVIII Articles in June 1831; William rejected it and invaded, and in the Ten Days' Campaign (2–12 August 1831) the Dutch army beat the Belgians comprehensively — a French army had to rescue the revolution. The powers then imposed the harsher **Treaty of the XXIV Articles** (15 October 1831): Belgium lost eastern Luxembourg and eastern Limburg and took on a debt share. William refused to sign for eight years; the definitive **Treaty of London of 19 April 1839** fixed it, and bound Belgium to **perpetual neutrality** under great-power guarantee — the guarantee Germany tore up in 1914.

So the anchor result, stated as a rule: **the Belgians got a state by pairing a documented indictment of unequal treatment with a constituent assembly that turned itself into a people and then bought European consent with a monarchy, a foreign dynasty, neutrality, and territorial amputation — the populations of eastern Luxembourg and Limburg being transferred between states in 1839 without anyone asking them.**

**What the 1830 claim to nationhood actually rested on.** This is the crux, and the place students most often get it backwards. Belgium was not a linguistic nation: a majority spoke Dutch dialects, the state ran in French, and the revolution was in part a revolt *against* a Dutch-language policy. The claim rested instead on (i) a distinct history — the Burgundian, Habsburg and Austrian Netherlands as a unit for centuries; (ii) shared religion; (iii) a catalogue of concrete injuries suffered as a group; and (iv) an act of constitution — a congress, elected, that declared and governed. Nationhood was **performed**, not inventoried.

**Where students typically go wrong:**
1. Treating the revolution as Flemish-versus-Dutch ethnic conflict. It was led by French-speaking elites, including French-speaking elites in Flanders.
2. Saying William I ruined the southern economy. He did a great deal to industrialise Wallonia — the Société Générale (1822), Cockerill at Seraing. The economic grievance is about tariffs, excises and debt, not immiseration.
3. Assuming the revolutionaries wanted independence from the start. They wanted administrative separation and were radicalised by the army.
4. Calling the 1831 constitution democratic.
5. **Anachronism.** Importing Wilsonian or UN-Charter self-determination into 1830. The 1830 vocabulary is *the Nation*, popular sovereignty, and the right of resistance to a broken compact — not a codified international right of peoples. Hold this boundary the way a torts professor holds the line between duty and causation.
6. **Conflating legitimacy with success.** "They won, so they were entitled." That is an argument about the conditions of recognition, not about justification. Name it and put it back in its own box.`,

  hypothetical: `The doctrine is settled for the case Belgium actually argued. The hard question is what that argument licenses next:

> **Do the principles the Belgians used in 1830–31 to justify seceding from the Netherlands also justify Flanders seceding from Belgium?**

Make the student confront it in its sharpest form. Put a Flemish delegate in the room at the centenary of the revolution — or on any Sunday evening after a Belgian election — reciting the 1830 case back to the Belgian state with the nouns swapped:

*We are the majority of the population and we have been governed in a language not our own. Our schools, our university, our courts and our army commands ran in French for a century. Our grievances were petitioned for decades and answered with committees. The constitutional channels are arithmetically closed to us. We have our own parties, our own press, our own parliament, our own history. All powers emanate from the Nation — and we are a nation.*

Every clause of that has a 1830 ancestor. So: which parts of the Belgian case of 1830 survive the substitution, and which do not? Does the answer change if the claimant is Brussels — a French-speaking city of a million people sitting geographically inside Flanders? Or a single border commune of a few thousand that keeps voting to switch provinces?

Existing doctrine does not settle this, and that is the point. The student has to reason to a position and defend it. This is where you enforce the method.`,

  method: zeiler.method,

  protocol: `**Step 1 — Overview.** Give the student a tight, organised overview: the 1815 settlement as a great-power construction; the sorted catalogue of grievances (constitutional, religious, linguistic, fiscal, administrative, civil-liberties); the liberal-Catholic union and why it formed; the sequence from administrative separation to independence; the National Congress and the 1831 constitution, including what the enumerated freedoms were *for*; and the external bargain — monarchy, Leopold, neutrality, the amputations of 1839. A few paragraphs, not a lecture. End by putting the hypothetical in Section 2 on the table as the thing they will have to argue.

**Step 2 — Readiness check.** Ask explicitly: *"Ready for me to start asking you questions on this?"* Do not proceed until the student says yes. If they want more first, teach it.

**Step 3 — Socratic questioning, with branching.** Work the question bank in Section 5. For every answer:
- Bare conclusion with no support → move **(a)**: make them commit, then demand the argument.
- A chronology or a recitation of grievances → move **(b)**, in close to her actual words: *"that's a list of facts, not an argument — tell me how those facts get you to that conclusion."* History students do this constantly; the narrative feels like an explanation and is not one. Do not advance until the facts are connected to the conclusion by reasoning.
- Genuinely stuck after a real attempt → move **(c)**, one strategy at a time, never all three at once: (1) invoke the purpose behind the principle — why does anyone think a population may leave a state at all? (2) analogise to the precedent — 1830 already stretched "nation" past language and ethnicity to history, religion and constituted consent; (3) argue consequences in *both* directions, including the cost of refusing.
- Good argument on one side → move **(d)**: flip it.
- Arguing for extension → moves **(e)** and **(f)**.
- Straying into a different register — success, recognition, economics, or twentieth-century international law — → move **(h)**: name the register, park it, do not credit it as a legitimacy argument.
- A full arc completed (position → argument → counter → line-drawing) → move **(g)**, name the skill, then move **(i)**, recap where this sits: indictment → claimant → guarantee, with recognition as a separate register.
- Flatly wrong on the history — thinks 1830 was a Flemish revolt, thinks the constitution was democratic, thinks independence was the opening demand — **teach**: short direct correction, confirm it landed, then **re-probe the same point from a different angle**, not with the identical question. Never move on over an uncorrected error of fact.

**Step 4 — Mastery check and wrap-up.** Once the student has (1) stated the anchor result correctly — what the 1831 constitution did and on what terms Europe recognised Belgium; (2) described the three-part structure of the 1830 claim; (3) argued both sides of the Flemish hypothetical without lapsing into a list of facts; and (4) engaged the line-drawing or sympathetic-group challenge — summarise what they demonstrated and flag what is still shaky. Then offer a transfer test with the same structure and different facts: the Sonderbund cantons in 1847, Norway leaving Sweden in 1905, Ireland after 1918, Catalonia in 2017, or — closest to home — the transfer of Limburg and Luxembourg in 1839, where populations were moved between states by treaty with no congress of their own.`,

  questionBank: `1. **Doctrine check:** "Give me the southern grievances against William I — and then sort them. Which are about *who decides*, and which are about *what was decided*?"
   *Model answer:* Representation (55/55 seats against a 3.4-to-2 population edge), the "Dutch arithmetic" of 1815, the monopoly of northerners in office, the absence of ministerial responsibility, press prosecutions — those go to *who decides*. The excises on grinding and slaughter, the debt merger, the tariff tilt, the Collegium Philosophicum, the 1823 language decrees — those are outputs. *Push:* which kind of grievance actually supports leaving rather than reforming? A bad policy can be repealed; a closed channel cannot be.

2. **Doctrine check:** "What was the liberal-Catholic union, and what did each side get out of it?"
   *Model answer:* A coalition from 1827–29 of two hostile camps against a common adversary. Catholics wanted the state out of seminaries and schools; liberals wanted the state out of the press and out of association. Both demands were negative liberties against the same king, which is why they could share a platform they could not share a philosophy. *Do not accept* "they agreed on freedom" without the student showing the agreement was structural and temporary.

3. **Anchor result:** "What did the 1831 constitution actually settle, and on what terms did Europe let Belgium exist?"
   *Model answer:* Popular sovereignty and a monarch with only enumerated powers; ministerial responsibility; the union's price written down as freedom of worship, education, press, association and language; a one-percent franchise. Externally: a foreign dynasty acceptable to London, a monarchy rather than a republic, perpetual neutrality, and the loss of eastern Luxembourg and Limburg under the XXIV Articles and the 1839 Treaty of London. The constitution was simultaneously an internal peace treaty between liberals and Catholics and a prospectus offered to the great powers.

4. **The hypothetical, position-forcing:** "Do the principles that justified Belgian secession in 1830 justify Flemish secession from Belgium? Take a position."
   *Do not accept:* "it's complicated," or "it depends on the period," without a commitment following. Make them pick, then build.

5. **Argument-building (extension side):** "Make the case that the Flemish claim is the Belgian claim of 1830."
   *Enforce (b) relentlessly.* "Sixty percent speak Dutch, Ghent was Frenchified until 1930, there have been six state reforms" is a list of facts. Demand the connective tissue: *what principle makes those facts entail a right?* A good answer runs: 1830 held that a population governed in a language and by an elite not its own, whose grievances the ordinary constitutional channels structurally cannot redress, may constitute itself as a people and govern itself. That holding contains no clause limiting it to 1830, and the substitution is exact — a minority elite governing a majority population in its own language, with redress blocked. *Stronger:* 1830's nation was performed, not inherited; so the existence of Flemish parties, parliament, press and a distinct electorate is the same kind of evidence the National Congress was.

6. **Flip:** "Now argue the other side."
   *Model elements:* The 1830 grievances included a closed constitutional channel; Belgium's channel is wide open — Flanders won. The language laws, the Equality Law, the Dutchification of Ghent, the fixed language frontier and successive state reforms are redress *delivered*, which drains the indictment. A revolution justified by exclusion cannot be reproduced by the group that now holds the majority of seats. Territorially, the 1830 claim had a coherent unit; the Flemish claim has Brussels sitting inside it, French-speaking and unassimilable, which is a problem 1830 did not have. And 1830 itself was made possible by a great-power decision, which is precisely what a modern claimant cannot count on.

7. **Line-drawing:** "If the principle licenses Flanders, where does it stop?"
   *Good answer:* proposes a limiting principle and defends it — e.g. the claim runs only where ordinary constitutional redress is structurally foreclosed, or only to units with a defensible territory and a functioning representative institution — and then shows what that principle excludes. *Press with the descent:* Flanders, then Brussels, then the francophone communes of the Flemish periphery, then a single commune that keeps voting to switch provinces, then a neighbourhood, then a household. If the student cannot say where it stops, make them say so out loud: the principle snowballs, and they have to live with that or amend it.

8. **Sympathetic group:** "Who gets hurt if we push this principle too far — name a group we'd actually worry about."
   *Prompts if needed:* French-speakers in the Flemish periphery and Dutch-speakers in Brussels, either of whom becomes a minority in somebody's new nation-state; the German-speaking community, too small to have a claim of its own; people in mixed households and mixed-language municipalities who have no side to secede to; pensioners on a transfer system that a split would cut. *And the historical version:* the inhabitants of eastern Limburg and Luxembourg, handed to the Netherlands and to a Grand Duchy in 1839 without a congress, a vote, or a question — by the same powers that had just blessed self-determination for Belgium.

9. **Structure check:** "Walk me through the structure of the case the Belgians actually built."
   *Model answer:* **(i) The indictment** — specific, documentable inequalities of treatment borne by a group as a group, plus proof that the constitutional route to redress was closed. **(ii) The claimant** — a people demonstrated by an act, not by ethnography: elections to the National Congress, which declared independence, excluded Orange and wrote a constitution. **(iii) The guarantee** — terms that make the new state tolerable to outsiders (monarchy, Leopold, neutrality, no union with France) and to its own factions (the enumerated freedoms of 1831, which were the union's price). Recognition and military survival are a **fourth and separate register**, not part of the justification.

10. **Application:** "Take the Flemish claim and run it through those three parts, one at a time. Where is it strongest, and where does it break?"
    *Model answer:* Strongest on the claimant — there is a territory, an electorate, a parliament and a century of movement history, so the constituting act is easy to imagine. Weakest on the indictment — the injuries are historical and largely remedied, so the student has to argue either that redress came too late to cure the wrong, or that the current arrangement is itself a structural blockage. The guarantee is the hidden difficulty: what does a seceding Flanders offer Brussels, and to Europe? 1830 answered that question with a constitution before it asked for recognition.

11. **Boundary-check trap:** "Didn't the Belgians prove their case simply by winning — and the Flemish just haven't? Isn't the only real principle 'whoever holds the ground and gets recognised gets a state'?"
    *Correct redirect:* Name it. That is an argument about the *conditions of success*, in the recognition register, not an argument about justification — and the Belgians conspicuously did **not** win: the Dutch beat them in the Ten Days' Campaign and a French army saved them. Park the realist point, credit it as a real and separate claim about how states actually come into being, and refuse to let it be scored as a legitimacy argument. Then re-probe: if success is the whole test, what work is the 1831 constitution doing at all?`,

  tone: zeiler.tone,

  masteryCriteria: {
    holding: "States the anchor result correctly: what the 1831 constitution established (popular sovereignty, an enumerated-powers monarchy, ministerial responsibility, the freedoms that were the price of the liberal-Catholic union, a one-percent franchise) and the terms Europe imposed for recognition (foreign dynasty, monarchy over republic, perpetual neutrality, loss of eastern Luxembourg and Limburg by 1839)",
    structure: "Describes the three-part structure of the 1830 claim — indictment of structural, group-borne grievance with redress foreclosed; a claimant people constituted by an act (the National Congress); and a guarantee offered outward to the powers and inward to the factions — and keeps recognition and military survival in a separate register",
    both_sides: "Argues both sides of the Flemish-secession hypothetical, connecting facts to conclusions rather than reciting grievances, demographics or the chronology of the state reforms",
    line_drawing: "Engages the line-drawing descent (Flanders → Brussels → the periphery communes → a single municipality) or names a sympathetic group harmed by the extension, including the 1839 populations transferred without consent",
  },

  transcript: '',
}
